Netflix/mantis

mantis-server/mantis-server-worker/build.gradle
The `api` feature isn't compatible with this version of fatJar. This
causes problems when mantis workers try to load the
`io.mantisrx.server.worker.MantisWorker` class since it extends
`BaseService` which won't exist in the fatJar without `compile`.
=> Use `compile` vs `api`.

docs/mkdocs.yml
We can move to nav once we upgrade. For now, keep syntax consistent with
older version of mkdoc.
=> Use older mkdocs pages vs nav.

docs/docs/cli.md, docs/docs/mantisapi/index.md, docs/docs/writingjobs/index.md, docs/docs/writingjobs/source.md, docs/mkdocs.yml
Documentation-only changes: Fix internal links to account for "mantis/" subdirectory. Squish TOC hierarchy.
=> Additional documentation fixes

mantis-server/mantis-server-worker/Dockerfile, mantis-server/mantis-server-worker/src/main/resources/startup_docker.sh
Update the mantisagent in docker to download the mantis artifacts from mantisui. This allows us to create multiple different job clusters.
- [x ] `./gradlew build` compiles code correctly
=> Download job artifacts from mantis api in docker setup.

mantis-runtime/src/main/java/io/mantisrx/runtime/parameter/ParameterUtils.java
skip parameter if no param definition found
=> skip parameter if no param definition found

docker-compose-local.yml, mantis-server/mantis-server-worker/buildDockerImage.sh
A local docker compose file to be used while building docker images locally
- [x ] `./gradlew build` compiles code correctly
=> Added a local docker compose file that uses locally build docker images.

mantis-network/src/main/java/io/reactivex/mantis/network/push/LegacyTcpPushServer.java, mantis-network/src/main/java/io/reactivex/mantis/network/push/PushServerSse.java, mantis-remote-observable/src/main/java/io/reactivex/mantis/remote/observable/RemoteRxServer.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/TestSseServerFactory.java
Replace the deprecated way of setting netty low and high water marks.
=> Update the way we set Netty low and high water marks

docs/docs/mantisapi/index.md
Added missing sample response payloads for various mantis api methods.
=> add sample response bodies in the mantis api documentation

docker-compose.yml, mantis-server/mantis-server-worker/Dockerfile, mantis-server/mantis-server-worker/build.gradle, mantis-server/mantis-server-worker/buildDockerImage.sh
Includes updating Dockerfile Mesos refs to 1.1.3 and updating the JDK
image to Azul JDK 8 and fixing migration bugs along the way.
The JDK 8 image runs Ubuntu Xenial (which is more in line with our testing infrastructure) as opposed to an older version on Debian.
=> Update Mesos to 1.1.3.

mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageScalingPolicy.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/WorkerMetricHandler.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/WorkerMetrics.java
RPS is a measure of onNext / metricsInterval. This provides a measure of
work which can be used to autoscale via Clutch.
We need an abstract measure of "work" being done by a Mantis job. In the past RPS has been useful for this, and the first iteration of clutch actually used RPS. Our issue there was correctly selecting an RPS value was tricky and it was only present for Kafka jobs. We've since learned;
- How to select setpoints by recording sketches and using percentiles.
- How Lag/Drops can be incorporated into RPS in a manner that a PID understands.
=> Added RPS metric for autoscaler.

mantis-common/src/main/java/io/mantisrx/common/WorkerPorts.java, mantis-common/src/test/java/io/mantisrx/common/WorkerPortsTest.java
Mantis Master uses the legacy constructor. This is now tested and
documented right in the test.
Intent is to add validation to this class so we can validate it from the
Master side when it goes to initialize running workers. If validation
fails, this is considered a precondition which the Master will fail out
the worker. All invalid workers will be resubmitted together after the
launch sequence so they can try to get new port allocations.
=> Add validator for `WorkerPorts`.

mantis-common/src/main/java/io/mantisrx/common/WorkerPorts.java, mantis-common/src/test/java/io/mantisrx/common/WorkerPortsTest.java
Need at least 5 ports.
Mantis Master calls `WorkerPorts#new(List)` from
`SchedulingService#launchTasks`. If Mesos doesn't give it enough ports,
it will mark the launch as a failure and unschedule the worker
(`SchedulingService#unscheduleWorker`) right at that moment.
Keeping the `isValid` function in case a caller wants to use it.
=> Minor: Fail construction of `WorkerPorts` if not enough ports.

mantis-client/src/main/java/io/mantisrx/client/SseSinkConnectionFunction.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnectionFunction.java
Instead of creating a new metric group per connection, do it only once.
=> Create a single instance of MetricGroupId for SSE

gradle/wrapper/gradle-wrapper.properties, mantis-common/build.gradle, mantis-discovery-proto/build.gradle
switching jacksonVersion from 2.+ to 2.10.+ so we don't pull in higher versions like 2.11.0.rc1 etc which is incompatible with scala 2.13
=> set jacksonversion to 2.10.+ series

mantis-server/mantis-server-worker/build.gradle
Bumps the Mesos version for agents to match control plane.
Should be a noop. Seems the only related change is in https://github.com/apache/mesos/commit/2caff4036264301de767203f8ac8fd7ebf4017ee.
Diff doesn't have any other Java library changes https://github.com/apache/mesos/compare/1.7.2...1.3.2.
=> Bump Mesos version for agents.

mantis-runtime/src/main/java/io/mantisrx/runtime/executor/SinkPublisher.java, mantis-runtime/src/main/java/io/mantisrx/runtime/sink/Sink.java, mantis-runtime/src/main/java/io/mantisrx/runtime/sink/Sinks.java, mantis-runtime/src/test/java/io/mantisrx/runtime/executor/TestJobParameterized.java
- Add init method to sink interface. defaults to no op
- For multi sinks fix issue where parameters declared in the sinks weren't getting autopopulated
- [x ] `./gradlew test` passes all tests
=> Sink enhancements

mantis-runtime/src/main/java/io/mantisrx/runtime/sink/Sinks.java
Init call was not forwarded in wrapper sinks like multisink etc
=> Init calls on multisink and other sink wrappers

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MasterClientWrapper.java
SchedulingInfo is refreshed periodically, this creates excessive logs for large jobs. Turning down log level for worker assignments to DEBUG
=> log worker assignments at DEBUG

mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/DefaultIcebergWriter.java, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStage.java
We can use Iceberg's `LocationProvider` interface and implement the
ability for users to provide different table locations. This is useful
in a cluster island-model setup, for example in AWS east/west/eu. Each
of these clusters might have table locations with different paths such
as `s3n://prod-data` (main, r/w), `s3n://prod-west-replica1-data`, and
`s3n://prod-eu-replica2-data`. If we had only one table location, eu and
west would write `DataFile`s cross-region over to the east location. By
specifying different locations, each region can write to their local
location, then, some other service can asynchronously replicate over to
the main (east) region in a separate runtime path.
This way, we can reduce/mostly avoid huge cross-regional latencies when
writing DataFiles.
=> Add `LocationProvider` for table location support.

mantis-control-plane/Dockerfile, mantis-control-plane/buildDockerImage.sh, mantis-examples/mantis-examples-mantis-publish-sample/Dockerfile, mantis-examples/mantis-examples-mantis-publish-web-sample/Dockerfile, mantis-server/mantis-server-worker/Dockerfile
Adds a caching layer to reduce rate limit behavior from the public
Docker Hub; goes into effect November 01, 2020. See
https://docs.docker.com/docker-hub/download-rate-limit/ for more info.
=> Use Netflix Docker Hub container image registry.

mantis-server/mantis-server-worker/build.gradle
bump mantis-rxcontrol version to pick up stream double consume fix in ClutchConfigurator
=> pin mantis-rxcontrol to pick latest patch version

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/MesosDriverSupplier.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/VirtualMachineMasterServiceMesosImpl.java
more logging around mesos scheduler driver init
=> add more logging for mesos scheduler driver init

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/MesosDriverSupplier.java
Block till scheduler driver is initialized, retry when failed to initialize driver within 5 seconds
=> block till mesos scheduler driver is initialized

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/MesosDriverSupplier.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/VirtualMachineMasterServiceMesosImpl.java
bound max time to wait for scheduler driver init
=> bound max time to wait for scheduler driver init

build.gradle, mantis-examples/mantis-examples-mantis-publish-sample/build.gradle, mantis-examples/mantis-examples-mantis-publish-web-sample/build.gradle
This replaces jcenter with maven central
Also noticed that artifacts from `net.andreinc.*` are in use for some mantis samples and those are in jcenter only. I went ahead and create a backup in our own repos so when jcenter goes away, we will be fine
=> Replace jcenter with maven central

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-network/src/test/java/io/reactivex/mantis/network/push/TimedChunkerTest.java, mantis-publish/mantis-publish-core/build.gradle
Change meaning of resubmission limit to take time duration into account. For long running jobs that may run for months or years, worker resubmissions will eventually reach the limit. We don't want to penalize such jobs. We should only terminate jobs where workers are resubmitted constantly. That may be due to bad code or external dependency failures.
=> Change meaning of resubmission limit to take time duration into account

baseline.gradle, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/MantisAgent.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/MetricsClient.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/MetricsClientImpl.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnectionFunction.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/WorkerMetricsClient.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/example/SampleClient.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/TestSseServerFactory.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/client/MetricsClientImplTest.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/client/SseWorkerConnectionFunctionTest.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/client/SseWorkerConnectionTest.java
Applying autoformatting to all subprojects under mantis-server
=> applying formatting to all subprojects under mantis-server

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
Handle null ptr exception for `KillJobRequest.requestor`. This can happen when the requestor is cluster manager actor itself e.g. worker resubmit count exceeded case.
=> Handle nullptr on killJobRequest requestor

mantis-connectors/mantis-connector-iceberg/build.gradle, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/config/SinkConfig.java, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStage.java, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/config/WriterConfig.java, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/pool/FixedIcebergWriterPool.java, mantis-connectors/mantis-connector-iceberg/src/main/resources/log4j.properties, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergTableExtension.java, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterEndToEndTest.java, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStageTest.java, mantis-connectors/mantis-connector-iceberg/src/test/resources/log4j.properties, mantis-runtime/build.gradle, mantis-runtime/src/main/java/io/mantisrx/runtime/WorkerInfo.java
We have observed that the IcebergWriterStage can produce corrupted data files when the committer worker changes. This is because changes to the committer worker result in new subscriptions to the data file stream (`Observable<DataFIle>`) produced by the writer stage. The new subscriptions result in the input hot stream being consumed from a different thread than before, and since the data structures that parquet manages are not thread-safe, this leads to data file corruption.
As part of this change, we ensure that all the writes to the ParquetFileWriter are made from the same thread.
=> Making the IcebergWriter always use 1 thread for writing to the data file

.gitignore, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/StreamManager.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/api/StreamType.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/internal/mql/MQLSubscription.java, mantis-publish/mantis-publish-core/src/test/java/io/mantisrx/publish/AbstractSubscriptionTrackerTest.java
We experienced a bug in production in which the `mreAppJobClusterMap`
uses `__default__` as the routing key when a stream does not have a
routing entry. These routing keys are internally used as stream names,
however internally mantis-published used `defaultStream`. This commit
reconciles these two by renaming defaultStream to `__default__`.
`
More work to come in the future to avoid conflation of routing keys and
stream names.
=> Rename defaultStream to __default__.

mantis-connectors/mantis-connector-kafka/build.gradle, mantis-control-plane/mantis-control-plane-client/build.gradle, mantis-network/build.gradle, settings.gradle
I want to get the mantis OSS repo ready for gradle 7.0. This means we will have to get rid of deprecated rules/configurations in build files. 
^^^
=> Enabling build scans and getting rid of deprecated configurations in build files

.github/workflows/nebula-ci.yml, gradle.properties
Gradle cache is a fairly mature feature right now and has been battle-tested at Netflix and other places. Thus, enabling this feature in the mantis repo in the hope that it would help reduce build times.
=> Enabling gradle cache for the whole repository in order to speed up the builds

.github/workflows/nebula-ci.yml, gradle.properties, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/AbstractSubscriptionTracker.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/DefaultSubscriptionTracker.java, mantis-publish/mantis-publish-core/src/test/java/io/mantisrx/publish/AbstractSubscriptionTrackerTest.java, mantis-publish/mantis-publish-core/src/test/java/io/mantisrx/publish/DefaultSubscriptionTrackerTest.java
Unreverted the change to fix the max subscription bug. The issue with this code is that it does not recognize the stream named `__default__` coming from the job subscription map. Previously this was hidden by duplicate record keeping. The simplest possible change is to just treat `__default__` as `defaultStream` when looking up existing subscriptions. However this calls for a larger discussion around:
1. Sundaram's idea of introducing a data structure to represent Stream keys.
2. Calvin's proposal to remove `streamName` from `propagateSubscriptionChanges` altogether and simply have it manage all streams at once.
The relevant code is in 6f0dd7ce8aa0f82c3d865ce0cca17473167e8475.
=> Fix missing subscription bug max subs change

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/LeadershipManagerZkImpl.java
Add gauge to track whether an elected leader has finished the bootstrap process and becomes ready to serve requests.
This helps determine when a leader gets elected successfully but fails to finish bootstrap to be in the ready state.
=> Add isLeaderReadyGauge

mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/AbstractSubscriptionTracker.java
This log will currently make all default stream users have a repeated warning log from the default stream mapping process. Moving to debug for now.
=> Make defaultStream Mapping check log debug level

mantis-client/src/main/java/io/mantisrx/client/SinkClientImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
If workers are resubmitted too frequently within a time period, the job is automatically terminated. However, there are scenarios where workers are supposed to be resubmitted, such as moving mesos clusters. We should only count resubmissions that are due to errors (worker is an error state and terminated unexpectedly).
=> Only count resubmission from worker failures

mantis-common/src/main/java/com/mantisrx/common/utils/MantisSSEConstants.java, mantis-runtime/src/main/java/io/mantisrx/runtime/sink/ServerSentEventRequestHandler.java
We have detected an issue internally that occurs with low probability. Connectors retrying an `IP:PORT` combination may connect to an unrelated job if that same `IP:PORT` combination is reused in a time frame less than the the client's expiration period. To address this we'll be making connection intentions explicit by passing a `sourceJobName` parameter when making a connection.
=> RTDI-2167 source job has incorrect subscriptions

mantis-client/src/main/java/io/mantisrx/client/SinkClientImpl.java
On stale connection issue, after checking the logs, `doOnUnsubscribe` was called. However, not all the connections were closed. There is likely an exception somewhere. The old exception catch doesn't do anything. It should at least log.
I also added another safe guard to terminate the inner observable once the sink is permanently closed.
=> SinkClient fix logging on unsubscribe

build.gradle, mantis-control-plane/mantis-control-plane-core/build.gradle, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/worker/TaskExecutorGateway.java
The goal of the gateway is to provide an interface for the control plane to communicate with the task executor. The control plane is expected to communicate with the task executor using RPC instead of HTTP as the task executor is not exposed outside.
=> [Part 2] Introducing Task Executor Gateway

build.gradle, mantis-common/build.gradle, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStage.java, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergTableExtension.java, mantis-connectors/mantis-connector-kafka/build.gradle, mantis-connectors/mantis-connector-publish/build.gradle, mantis-discovery-proto/build.gradle, mantis-examples/mantis-examples-jobconnector-sample/src/main/java/com/netflix/mantis/samples/JobConnectorJob.java, mantis-examples/mantis-examples-jobconnector-sample/src/main/java/com/netflix/mantis/samples/stage/EchoStage.java, mantis-examples/mantis-examples-mantis-publish-sample/src/main/java/com/netflix/mantis/examples/mantispublishsample/proto/RequestEvent.java, mantis-examples/mantis-examples-twitter-sample/src/main/java/com/netflix/mantis/examples/wordcount/sources/TwitterSource.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/JobMasterService.java, mantis-shaded/README.md, mantis-shaded/build.gradle
Currently, we depend on the local copy of jar (subproject) for mantis-shaded dependency. However, this leads to problems with IntelliJ where you have to manually add the mantis-shaded subproject as an explicit library dependency at the root OR deal with a bunch of redlines for these shaded components.
We tried a bunch of alternatives like publishing to local maven or including these shaded dependencies at the terminal level (leaf projects) and they open-up more issues. We decided to host mantis-shaded in a separate repo but we think this could be a better alternative 
- [*] `./gradlew build` compiles code correctly
- [*] Added new tests where applicable
- [*] `./gradlew test` passes all tests
- [*] Added copyright headers for new files from `CONTRIBUTING.md`
=> Depend on remote artifacts for mantis-shaded instead of local subproject

build.gradle, mantis-client/src/main/java/io/mantisrx/client/MantisClient.java, mantis-client/src/main/java/io/mantisrx/client/StageWorkersCount.java, mantis-client/src/main/java/io/mantisrx/client/examples/ConnectToNamedJob.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServices.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterClientApi.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterGateway.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MasterClientWrapper.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/SimpleSchedulerObserver.java, mantis-control-plane/mantis-control-plane-client/src/test/java/io/mantisrx/server/master/client/MasterClientWrapperTest.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/Configurations.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/WorkerMetricsClient.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
Refactored all usages of the mantis mantis client to make use of the interface instead of the actual implementation.
=> [Part 3] Refactoring Mantis Master Client code into a Gateway interface that defines the spec and a curator based implementation that matches that.

build.gradle, mantis-common/build.gradle, mantis-common/src/main/java/io/mantisrx/common/WorkerPorts.java, mantis-common/src/test/java/io/mantisrx/common/WorkerPortsTest.java, mantis-common/src/test/java/io/mantisrx/common/compression/CompressionUtilsTest.java, mantis-connectors/mantis-connector-iceberg/build.gradle, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterEndToEndTest.java, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStageTest.java, mantis-connectors/mantis-connector-kafka/build.gradle, mantis-connectors/mantis-connector-kafka/src/test/java/io/mantisrx/connector/kafka/sink/KafkaSinkTest.java, mantis-connectors/mantis-connector-kafka/src/test/java/io/mantisrx/connector/kafka/source/KafkaSourceTest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/VirtualMachineMasterServiceMesosImpl.java, mantis-runtime/src/main/java/io/mantisrx/runtime/WorkerInfo.java, mantis-runtime/src/test/java/io/mantisrx/runtime/TestWorkerInfo.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStageTest.java
This diff has two purposes:
1. Establish the semantics of WorkerPorts and make sure all constructors lead to the same behavior (which was not the case before)
2. Make sure WorkerPorts is serializable by both Jackson and Java as it will be sent via wire using java serialization during RPC calls.
=> [Part 4]: Clean up worker ports

mantis-client/src/main/java/io/mantisrx/client/SinkClientImpl.java, mantis-common/src/main/java/io/mantisrx/common/compression/CompressionUtils.java, mantis-common/src/test/java/io/mantisrx/common/compression/CompressionUtilsTest.java
There is a bug in CompressionUtils if the delimiter has a prefix that matches the end of a segment, the data is not properly tokenized.
=> Fix bug in CompressionUtils that fails with certain delimiters

.editorconfig, .github/CODEOWNERS, build.gradle, mantis-common/build.gradle, mantis-common/src/main/java/com/mantisrx/common/utils/Closeables.java, mantis-server/mantis-server-worker/build.gradle, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/BlobStore.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/BlobStoreAwareClassLoaderHandle.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/HadoopFileSystemBlobStore.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/BlobStoreTest.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/TestBlobStore.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/TestHadoopFileSystemBlobStore.java
Two features are added through this change.
1). Firstly, I'm introducing a new blob store abstraction and a few implementations that can help download the blob from various stores such as s3, artifactory, etc.
2). A new class loader implementation has also been added to use the blob store to download the requested artifacts from s3 or artifactory or elsewhere and create a class loader object that can run the user's application code.
In the new Titus world, one can use the cluster to run any user-submitted mantis job. Thus, we need capabilities to both download artifacts on demand and load them into the JVM to run the user's mantis job. This diff adds some of the abilities required for the above functionality.
=> [Part 6]: Blob Store abstractions and a classloader factory that uses the blob store

mantis-common/src/main/java/com/mantisrx/common/utils/Services.java, mantis-common/src/main/java/io/mantisrx/common/WorkerPorts.java, mantis-common/src/main/java/io/mantisrx/runtime/MantisJobState.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServices.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/ResourceLeaderConnection.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusterGatewayClient.java, mantis-server/mantis-server-worker/build.gradle, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ExecuteStageRequestService.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Hardware.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/JvmUtils.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MachineDefinitionUtils.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Task.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/TaskExecutor.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/config/WorkerConfiguration.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/Point.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/ResourceManagerGatewayCxnTest.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/SineFunctionJobProvider.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/TaskExecutorTest.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/TestingRpcService.java
So far, we have seen several classes on the worker side that are meant to help with the on-demand task execution. This diff introduces the task executor class that binds all these classes to implement the gateway.
=> [Part 7]: Introducing the Task Executor

docs/docs/develop/writing-jobs/group-by.md, docs/docs/develop/writing-jobs/twitter.md, docs/docs/develop/writing-jobs/word-count.md, docs/docs/getting-started/concepts.md, docs/docs/getting-started/samples/on-demand.md, docs/docs/getting-started/samples/sine-function.md, docs/docs/getting-started/samples/twitter.md, docs/docs/getting-started/tutorials/local.md, mantis-examples/README.md, mantis-examples/mantis-examples-twitter-sample/build.gradle
The git repository `mantis-examples` has been deprecated and has been moved to the central `mantis` repository (this). However, example code and links in documentation are still pointing to the old `mantis-example` repository. That could be confusing when people follow the link only to find the stale code.
This patch fixes the deprecated links, and also updates the commands to run those example jobs.
NOTE: there could be other stale links as we have deprecated multiple standalone repositories and moved them here. We should file new pull requests to fix that. This one is mainly for `mantis-examples`.
=> Link to latest mantis-example and update commands

mantis-common/src/main/java/io/mantisrx/common/metrics/MetricsPublisherNoOp.java, mantis-common/src/main/java/io/mantisrx/runtime/JobConstraints.java, mantis-common/src/main/java/io/mantisrx/runtime/MachineDefinition.java, mantis-common/src/main/java/io/mantisrx/runtime/NamedJobDefinition.java, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/SchedulingInfo.java, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageSchedulingInfo.java, mantis-common/src/main/java/io/mantisrx/runtime/parameter/Parameter.java, mantis-common/src/test/java/io/mantisrx/runtime/MachineDefinitionTest.java
All the changes as part of this diff are minor.
=> Bunch of spurious changes to make various classes serializable via java serialization

mantis-common/build.gradle, mantis-common/src/testFixtures/java/io/mantisrx/common/util/DelegateClock.java, mantis-control-plane/mantis-control-plane-core/build.gradle, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/WorkerId.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusterTaskExecutorMapper.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusters.java, mantis-control-plane/mantis-control-plane-core/src/testFixtures/java/io/mantisrx/server/core/TestingRpcService.java, mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterGatewayAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/IMantisStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisStorageProviderAdapter.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/SimpleCachedFileStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/MantisStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/NoopStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/SimpleCachedFileStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/TaskExecutorStateTest.java, mantis-server/mantis-server-worker/build.gradle, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/SubscriptionStateHandlerImplTest.java, mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/TaskExecutorTest.java
Resource Cluster is a new abstraction to capture all the task executors that are registered with the mantis master.
=> [Part 15]: Resource Cluster Abstraction and an implementation based on Akka actor

mantis-shaded/build.gradle
Move Jackson version to "1.12+".
=> Upgrade jackson version in shaded jar

mantis-remote-observable/src/main/java/io/reactivex/mantis/remote/observable/DynamicConnectionSet.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/SinkPublisher.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/StageExecutors.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/WorkerConsumer.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/WorkerConsumerRemoteObservable.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/WorkerPublisher.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/WorkerPublisherRemoteObservable.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/DataDroppedPayloadSetter.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ResourceUsagePayloadSetter.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
Before both the APIs were not available, we would get rid of the container as part of shutting down the workload. In the new Titus world, we want to gracefully shut down all the resources associated with the stage execution.
=> [Part 12] Calling Source::close, Sink::close as part of stage execution

.editorconfig, .github/workflows/test-results.yml
https://github.com/EnricoMi/publish-unit-test-result-action/blob/v1.20/README.md#support-fork-repositories-and-dependabot-branches
=> Adding new workflow to publish test results

mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/SimpleCachedFileStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/LeaderRedirectionRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/AgentClusterRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobClusterRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/AdminMasterRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/AgentClustersRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobClustersRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobDiscoveryStreamRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobsRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/RouteTestBase.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerTest.java
Should fix the flakiness affecting multiple builds such as https://github.com/Netflix/mantis/pull/171
=> Fixing flaky tests

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
This change purely has some additional tests for the resource cluster actor.
=> Adding tests for Resource Cluster Actor

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
Resource Cluster Manager Actor is responsible for managing all resource clusters. Think of it as the supervisor actor for the Resource Cluster Actor.
=> Resource Cluster Manager Actor

mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/committer/config/CommitterConfig.java, mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/config/WriterConfig.java, mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/StageOverrideParameters.java, mantis-runtime/build.gradle, mantis-runtime/src/main/java/io/mantisrx/runtime/parameter/Parameters.java, mantis-runtime/src/test/java/io/mantisrx/runtime/parameter/ParametersTest.java
https://github.com/Netflix/mantis/pull/170#issuecomment-1098264092
> It looks like we should be using Parameters::get without the default value in this case. That would surface the runtime exception and hence the problem in this case.
=> Iceberg sink uses Parameters::get to ensure parameter definition exists

mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Heartbeat.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Task.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/TaskExecutor.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
Every heartbeat sent from the new task executor will contain the hostname from which it is sent. Note that this field already exists but wasn't used by the Mesos-based task executor. The new task executor will use it.
=> Setting hostname as part of heartbeat

.github/CODEOWNERS, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/LabelManager.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/ExecuteStageRequestFactory.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactory.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactoryImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareScheduler.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
This diff introduces a new scheduler based on resource cluster fundamentals.
=> Resource Cluster Aware Scheduler Introduction

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerService.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/MantisMasterAPI.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/AgentClusterRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobClusterRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobDiscoveryRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobStatusRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/AgentClustersRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobClustersRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobDiscoveryStreamRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobsRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobManagerTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerTest.java
This integrates the new federated scheduler factory that can schedule jobs on both mesos and the new task executors with the mantis master.
=> Scheduler Integration with Mantis Master

mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/MasterApiAkkaService.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/MantisMasterRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/BaseRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersReadRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersWriteRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/LeaderRedirectionFilter.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/MantisMasterAPI.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobsRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterReadRouteTest.java
=> Adding API routes for various resource cluster related actions

mantis-shaded/build.gradle
I need the DateTime Module for Jackson as I would prefer to have a consistent way to serialize/deserialize these types.
=> Add extra dependency for mantis-shaded

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/TestGetMasterMonitor.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/master/ZookeeperMasterMonitor.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/zookeeper/CuratorService.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
There's no need for the master description value to be seeded given that it can be obtained directly from the zookeeper. That's what this diff does.
=> Making sure zookeeper master monitor doesn't need a seed value for master description

build.gradle
=> Upgrading mantis-shaded

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/CoreConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
One of these properties is a prefix of the other. This works when defined in properties file but it doesn't when we want the props to be expressed in another DSL such as YAML.
=> Making sure there's a distinction between metrics publisher and metrics publisher's publish frequency

mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
=> Using first instead of single in Mantis Worker

mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Task.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/TaskExecutor.java
In the new model, we don't use the publish subject that's created by the Mesos callback handler. However, this is required in the old model. Thus, this diff fixes the issue.
=> Use the same subject returned by the mesos callback handler

mantis-common/src/main/java/io/mantisrx/common/WorkerPorts.java, mantis-common/src/main/java/io/mantisrx/runtime/MachineDefinition.java, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/SchedulingInfo.java, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageScalingPolicy.java, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageSchedulingInfo.java, mantis-common/src/main/java/io/mantisrx/runtime/parameter/Parameter.java
I had forgotten to add serial version uids to all transitive data structures in the previous PR https://github.com/Netflix/mantis/pull/219. This diff addresses that.
=> Adding serialverisonuids to all transitive data-structures

mantis-publish/mantis-publish-core/build.gradle, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/internal/discovery/mantisapi/DefaultMantisApiClient.java, mantis-publish/mantis-publish-core/src/test/java/io/mantisrx/publish/internal/discovery/mantisapi/DefaultMantisApiClientTest.java, mantis-publish/mantis-publish-core/src/test/resources/mantisapi/jobclustermap_stub.json, mantis-publish/mantis-publish-core/src/test/resources/mantisapi/jobclusters_discoveryinfo_stub.json
Switched DefaultMantisApiClient from ObjectMapper to JsonSerializer as part of https://github.com/Netflix/mantis/issues/194 . I also moved the testing code to a test class, and tested the change manually against our production api server and a source job.
=> Consolidation ObjectMapper Usage (Step 4)

mantis-network/src/main/java/io/reactivex/mantis/network/push/ObservableTrigger.java
There is an implicit assumption that subscription should be 1. Before, the subscriptionActive gauge is always set to 1 whenever there is at least 1 subscription. I change that to increment/decrement on subscribe/unsubscribe to more accurately reflect the number of subscriptions. Before, the unsubscribe was purposely commented out. Clearly, this can lead to multiple subscription, which violates the assumption. With this change, we will unsubscribe the old subscription when a new subscription is created. This should correct keep active subscription at 1.
=> Ensure there is only 1 subscription in PushTrigger

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/vm/AgentClusterOperations.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/vm/AgentClusterOperationsImpl.java
Started hacking into Agent Cluster Operations implementation to get it working for Titus implementation and realized there's some unused code. This diff gets rid of it.
=> Cleaning up unused code AgentClusterOperations

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
Convert hard-coded constant to a job init start timeout with larger value to compensate SBN job start time lag.
=> Add job init start timeout config

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/DisableTaskExecutorsRequest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/DisableTaskExecutorsRequestTest.java
Since DisableTaskExecutorsRequest doesn't have an ID, we need a way to represent a given request in the underlying storage medium uniquely. This adds that functionality.
=> Adding getHash() for DisableTaskExecutorsRequest

mantis-shaded/build.gradle
Without this change, it's impossible to serialize and deserialize Instant and other java.time.* data structures free of cost with Jackson.
=> Adding jsr310 module to serialize and deserialize Instant datastructure

mantis-common/src/test/java/io/mantisrx/runtime/descriptor/StageScalingPolicyTest.java
This particular serialization test made some assumptions about ordering the keys in a map. Since it uses a hashmap under the hood, the ordering is not guaranteed; hence, the test is flaky. This diff fixes that.
=> Cleaning up a newly written test that makes assumption around serialization ordering

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorRegistration.java, mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/master/resourcecluster/TaskExecutorRegistrationTest.java
I was noticing that taskExecutorContainerDefinitionId was getting serialized as part of the TaskExecutorRegistration state. This diff aims to get rid of that. 
```
"taskExecutorContainerDefinitionId": {
"resourceID": "some value"
}
```
=> Making sure container attribute field is not getting serialized as part of TaskExecutorRegistration

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
Currently, when the archive job cache tried to load any out-of-date archive job it will trigger an error thrown from the cache get and becomes an unhandled error (to radar detection as well).
Adding the IOException type to the catch clause to reduce the error noise.
=> Handle load archive job cache error

mantis-common/src/main/java/io/mantisrx/runtime/descriptor/DeploymentStrategy.java, mantis-common/src/test/java/io/mantisrx/runtime/descriptor/DeploymentStrategyTest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobDefinition.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/LabelManagerTest.java
Add support in job submission API to specify the target resource cluster. This change is supposed to be back-compat.
* Also making "labels" in JobDefintion to be unique on each label name.
=> Support resource cluster based job submission API

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/PagedActiveJobOverview.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterNonLeaderRedirectRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
Add API to fetch active jobs for a given resource cluster ID.
=> Support get active jobs per ResourceCluster

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
The ack returned to self() after the async pipe operation is redirected to the dead-letter actor since the self() reference is lost. I am removing the extra Ack from the call.
=> Fix dead letter Ack from RC scaler

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobClusterDefinitionImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobDefinition.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/NamedJob.java
On the jobCluster metadata, we store the list of previously deployed jars which can grow quite big. We'd like to force some constraints on this size to make it more manageable.
I'm also putting up a bugfix for when the labels map have multiple entries with the same key.
=> Truncate archive jarlist to not be more than 3

mantis-common/src/main/java/io/mantisrx/runtime/descriptor/SchedulingInfo.java, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageSchedulingInfo.java, mantis-common/src/test/java/io/mantisrx/runtime/descriptor/SchedulingInfoTest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/MantisResourceClusterSpec.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActorTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/SimpleFileResourceStorageProviderTests.java
* Move 'ContainerSkuID' and 'ClusterID' to common/contracts.
* Add 'ContainerSkuID' to 'StageSchedulingInfo' so it's available to the submit job APIs.
=> Add ContainerSkuID to StageSchedulingInfo

.github/workflows/nebula-snapshot.yml, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
This effectively reverts #245 where we introduced a null return value in load/get method for guava cacheloader which isn't liked. I'm using an optional return value instead with an explicit null on any exception.
=> Handle null return values in load/get call for guava cacheloader

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactory.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactoryImpl.java
When we receive non-terminal events (such as heartbeats) for jobs that are currently not running according to the control plane, we send them to the resource cluster specified in their job definition to decommission them. However, we ignore the event if there's a failure to load the job definition at this point. This diff changes this behavior to assume that all ghost workers that don't have corresponding job definitions belong to mesos.
=> Defaulting to the mesos cluster in case of non-terminal events with unknown job definitions

mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/MantisEventPublisher.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/api/EventPublisher.java
`EventPublisher::publish` has a method that publishes events to a default stream. `hasSubscriptions` should have a similar method that defaults to the same stream.
=> Provide a default implementation of EventPublisher::hasSubscriptions 

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/MesosDriverSupplier.java
Previously, the username for the executor was assumed to be user that's running the scheduler framework. However, in some instances, we would want to set the username directly. This diff allows one to do that.
=> Allowing the user to set the mesos executor username explicitly

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/LifecycleEventPublisherImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/LifecycleEventsProto.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
See these messages when the job was requested to be killed, but no more messages after that. 
```
2022-10-15 23:18:14.562  INFO 5863 --- [dispatcher-7242] i.m.m.j.JobClusterActor                  : JobClusterActor.onKillJobRequest KillJobRequest [jobId=RavenConnectorJob-1929614, reason=runtime limit reached, user=MantisMaster, requestor=null]
2022-10-15 23:18:14.563  INFO 5863 --- [dispatcher-7242] i.m.m.j.j.JobActor                       : Shutting down job RavenConnectorJob-1929614 on request by Actor[akka://MantisMaster/user/JobClustersManager/JobClusterActor-RavenConnectorJob#799277631]
```
=> Making sure there are extra logs when publishing events to other components fails

mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java
Reducing the scope of certain methods in RuntimeTaskImpl.
=> Making sure RuntimeTaskImpl does not expose certain methods.

mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/RuntimeTask.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Heartbeat.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
I think the server expects the hostname of a worker to be WorkerConfiguration::getExternalAddress (at least, that's what is set when the registration is sent; In mesos, this is set to the external IPV4). So, make sure we are using that consistently across the codebase. I'm also introducing a new method in WorkerConfiguration that also makes this the norm.
=> Getting rid of hostname that's getting passed to RuntimeLoader

mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/TaskFactory.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/SingleTaskOnlyFactory.java
Move getUserCodeClassLoader to have a default interface version.
=> Move getUserCodeClassLoader to interface default

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/master/ZookeeperMasterMonitor.java
The zk monitor can hit nullptr exception if no existing leader data is ready in zk.
=> Fix null exception on zk init

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/Status.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/akka/MantisActorSupervisorStrategy.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/worker/WorkerHeartbeat.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/worker/WorkerStatus.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareScheduler.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RunningWorker.java
Resource Cluster already maintains metadata around who is responsible for what. So, it doesn't need any additional metadata to figure out the host running the task that needs to be canceled. This diff aims to fix this behavior.
=> Resource Cluster Based Scheduler should be able to handle cancellation of running tasks without hostname

mantis-common/build.gradle, mantis-common/src/test/java/io/mantisrx/runtime/parameter/TestSerialization.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/SimpleFileResourceClusterStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/resourceprovider/SimpleFileResourceStorageProviderTests.java
Resource Cluster Storage Provider was making assumptions about what the root directory was for the resource cluster storage provider. This diff aims to get rid of these assumptions.
=> Making sure resource cluster storage provider does not assume the root directory

.github/workflows/nebula-snapshot.yml, mantis-examples/mantis-examples-jobconnector-sample/build.gradle
the current `pull_request_target` workflow checkouts the main branch rather than the PR head.
=> Fix build action

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/ArtifactID.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/JobArtifact.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/MasterApiAkkaService.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/Jackson.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/MantisMasterRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobArtifactRouteHandler.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobArtifactRouteHandlerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/HttpRequestMetrics.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/JobArtifactsRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobArtifactProto.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/MantisStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/NoopStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/SimpleCachedFileStorageProvider.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/MantisMasterAPI.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobArtifactSerdeTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobsRouteTest.java
Add JobArtifact model and storeNewArtifact function in StorageProvider interface
This PR aims to define the model for Job artifacts we plan to store going forward. A new functionality has been added to MantisStorageProvider to be able to store new job artifacts (right now it only saves 1 artifact at the time, maybe in the future we can store more than one at the time).
Note: before merging I plan to change `JobArtifact` model a bit to have a list of dependencies where the runtime is only 1 of the dependencies; can be empty if the artifact is in the form of a uber jar.
=> Add JobArtifact model and storeNewArtifact function in StorageProvider

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java
There are multiple places creating HA service instances and their own curator instance. A regression was introduced when some of the HA service creations no longer initialize/run their own curator service. 
The fix here is to consolidate and use a single HA service instance across all components and ensure the singleton instance will be ran.
=> Fix multiple HA sevice instance

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
Missed a few assumptions about naming that are present in mantis. Fixing pesky off-by-one errors.
=> fix off by one errors

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerTest.java
In an earlier diff, I think I slowed down loading all completed jobs causing timeouts during JobClusterActor init. This prevents master from launching if that job list is too big.
Speeding it up by using a different all rows API.
On closer inspection, I feel that completed jobs shouldn't be part of the JobClusterActor init and can be delayed—-ideally done async. I'll spend some time on that time next!
=> Improve fetch performance for completed jobs

mantis-common/src/main/java/io/mantisrx/common/metrics/Metrics.java
When running master we noticed metrics emitted by `JobClusterActor` (eg. numJobSubmissions) changed names in Atlas (internal monitoring system). It looked like the metric would contain custom tags as part of the name.
Example:
- metric name in latest running version was: `JobClusterActor_numJobSubmissions`
- metric name in master was: `JobClusterActor_jobCluster_<clusterName>_numJobSubmissions`
`jobCluster` is a custom tag we add in https://github.com/Netflix/mantis/blob/dd88c50fcde0902466fa45f36918de48cf67061f/mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java#L610 
I was able to repro the issue by running this simple snippet:
```
package io.mantisrx.common.metrics;
import com.netflix.spectator.api.BasicTag;
import …
```
=> Fix metric name issue

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/proto/JobClusterProtoAdapter.java
Remove dupe labels in job cluster create/update.
=> Fix dupe labels in job cluster create/update

.github/workflows/nebula-snapshot.yml, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/BaseService.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/LifecycleEventPublisherImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/LifecycleEventsProto.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerEventSubscriber.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerEventSubscriberLoggingImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerMetricsCollector.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerRegistryV2.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobState.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/events/WorkerRegistryV2Test.java
This diff aims to collect individual worker metrics such as 
1. How long it took to schedule a worker?
2. How long it took to prepare a worker?
3. How long a worker ran?
All these metrics are tagged with cluster names. This would help us differentiate mesos & titus schedule latencies, for instance.
=> Collect metrics with respect to worker transitions

mantis-runtime/src/main/java/io/mantisrx/runtime/sink/Sink.java, mantis-runtime/src/main/java/io/mantisrx/runtime/source/Source.java
Making close() implementation optional. The reason it's made optional is that we want users to migrate to Titus without any API changes. I will change this in the 3.0.0 release so that we can close sources and sinks appropriately.
=> I am making close() implementation optional. 

mantis-client/src/main/java/io/mantisrx/client/MantisClient.java
Need a constructor for MantisClient that allows one to supply the MantisClientWrapper.
=> Adding a new contructor for MantisClient

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerMetricsCollector.java
Fix NPE error event reported from control plane when workerId is not available in metrics collector.
=> [Minor] Fix npe in metrics collector

mantis-common/src/main/java/io/mantisrx/common/metrics/MetricsServer.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java
* MetricsServer uses metric group ID as measurement name, which doesn't work when common tags are set.
* In the non-Mesos job (task executor initiated jobs) the current metrics publisher is no-op but the metrics publisher instance created from CoreConfiguration causes loader trouble in the multi-loader (Titus + SB) case. I am disabling the no-op publisher for now and will follow up to see what the proper override/injection is for this case.
=> Fix metrics in non-mesos job

mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/DefaultIcebergWriter.java
Currently we use HadoopOutputFile interface to open data file to write. This limits the Iceberg data file has to use a Hadoop file system to open for write. As Iceberg FileIO is more flexible than that, we should use Iceberg native IO interface for opening files. For example, in Netflix set up, we use `S3FileIO` implementation to write to secure tables.
=> IcebergWriter uses table.io() to replace HadoopOutputFile

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManager.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/TaskExecutorStateTest.java
Currently, the TE allocation is greedy and uses the first TE with a machine size big enough for the request. Switching the allocation logic to use the min size available for the request instead.
=> Schedule TE in min sku

mantis-client/dependencies.lock, mantis-common/dependencies.lock, mantis-connectors/mantis-connector-job/dependencies.lock, mantis-connectors/mantis-connector-kafka/dependencies.lock, mantis-connectors/mantis-connector-publish/dependencies.lock, mantis-control-plane/mantis-control-plane-client/dependencies.lock, mantis-control-plane/mantis-control-plane-core/dependencies.lock, mantis-control-plane/mantis-control-plane-server/dependencies.lock, mantis-examples/mantis-examples-groupby-sample/build.gradle, mantis-examples/mantis-examples-jobconnector-sample/build.gradle, mantis-examples/mantis-examples-jobconnector-sample/dependencies.lock, mantis-examples/mantis-examples-mantis-publish-sample/dependencies.lock, mantis-examples/mantis-examples-sine-function/build.gradle, mantis-examples/mantis-examples-twitter-sample/build.gradle, mantis-examples/mantis-examples-wordcount/build.gradle, mantis-network/dependencies.lock, mantis-publish/mantis-publish-core/dependencies.lock, mantis-publish/mantis-publish-netty-guice/dependencies.lock, mantis-publish/mantis-publish-netty/dependencies.lock, mantis-runtime-loader/dependencies.lock, mantis-runtime/dependencies.lock, mantis-server/mantis-server-agent/dependencies.lock, mantis-server/mantis-server-worker-client/dependencies.lock, mantis-server/mantis-server-worker/dependencies.lock, mantis-shaded/build.gradle, mantis-shaded/dependencies.lock, mantis-source-jobs/mantis-source-job-kafka/dependencies.lock, mantis-source-jobs/mantis-source-job-publish/dependencies.lock
Bumping guava to a more recent version to use newer implementations. I need this PR to bump mantis-shaded which would tell me if there are any issues.
=> Bump guava to 31.+

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandlerAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/RuntimeTask.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationUtils.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationWritable.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/RuntimeTaskImplExecutorTest.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/WorkerConfigurationWritableTest.java, mantis-server/mantis-server-worker/build.gradle, mantis-server/mantis-server-worker/dependencies.lock, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/mesos/MesosMetricsCollector.java
To support customized task executor hosts e.g. Springboot the `RuntimeTask` interface dependencies need to have as thin dependencies as possible to avoid conflicts on the class loaders. This PR aims at removing most of the dependencies on this interface to have the parameters required in init to be mostly serializable to only rely on primitive types during class loading.
The impact of the change includes:
* RuntimeTask implementations will need to re-construct and manage components like HA services. (e.g. MantisMaster client).
* Bridging worker configuration handling to make it serializable until full config refactor. Picking metrics collector inside runtime task.
* Maintaining back compatibility for both Mesos and task executor hosts.
=> Refactor RuntimeTask Dependencies

.gitignore, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/MantisJobMetadataImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/MantisJobMetadataWritable.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/MantisStageMetadataWritable.java
Currently, we ignore duplicate workers for the same (jobId/stageNum/workerIdx) tuple. However, when we ignore these duplicate workers, we are essentially running a mantis master with a state that may not reflect the previous state of the master. This diff aims to surface these issues and block deployments to make sure we at least know when such problems happen. The current thinking is we should never see these issues. But, if we do see them, then the expectation is that we run state cleaner to clean up the state and then restart the master.
=> Setting preconditions to ensure we don't start mantis with an invalid state

docs/docs/getting-started/tutorials/docker.md
Hi! While going through the docs, I found a typo in the "Explore using Docker" section, so I thought I should submit a PR :)
=> fix typo in getting started with docker documentation

mantis-client/dependencies.lock, mantis-connectors/mantis-connector-job/dependencies.lock, mantis-connectors/mantis-connector-kafka/dependencies.lock, mantis-connectors/mantis-connector-publish/dependencies.lock, mantis-control-plane/mantis-control-plane-client/dependencies.lock, mantis-control-plane/mantis-control-plane-core/build.gradle, mantis-control-plane/mantis-control-plane-core/dependencies.lock, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/CleanupOnCloseRpcSystem.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/MantisAkkaRpcSystemLoader.java, mantis-control-plane/mantis-control-plane-server/dependencies.lock, mantis-examples/mantis-examples-mantis-publish-sample/dependencies.lock, mantis-publish/mantis-publish-core/dependencies.lock, mantis-publish/mantis-publish-netty-guice/dependencies.lock, mantis-publish/mantis-publish-netty/dependencies.lock, mantis-runtime-loader/dependencies.lock, mantis-server/mantis-server-agent/dependencies.lock, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutorStarter.java, mantis-server/mantis-server-worker-client/dependencies.lock, mantis-server/mantis-server-worker/dependencies.lock, mantis-source-jobs/mantis-source-job-kafka/dependencies.lock, mantis-source-jobs/mantis-source-job-publish/dependencies.lock
This PR aims to cleanup the temp folder where flink-rpc-akka jar is stored by `MantisAkkaRpcSystemLoader`. Both graceful and abrupt shutdown should be covered.
=> Close RpcSystem on TE shutdown

mantis-common/src/main/java/io/mantisrx/common/MantisProperties.java, mantis-network/src/main/java/io/reactivex/mantis/network/push/PushServer.java, mantis-network/src/main/java/io/reactivex/mantis/network/push/ServerConfig.java, mantis-runtime/src/main/java/io/mantisrx/runtime/parameter/ParameterUtils.java, mantis-runtime/src/main/java/io/mantisrx/runtime/sink/ServerSentEventsSink.java
This is an attempt to mitigate the stale connection issue from SSE server side. From observation, a stale connection is still reported as `active` but NOT `writable`. Therefore, we can allow the server to close the connection proactively if the channel remains not writable for an configurable amount of time.
=> Support NotWritable timeout on SSE connection

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/UpgradeClusterContainersRequest.java
Add a flag in upgrade cluster API to support skipping on existing containers on the target image id.
=> Upgrade API: add forceUpgradeOnSameImage flag

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/MantisStageMetadataImpl.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RunningWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
[User reported issue]
Some job nodes (mainly from non-source stage nodes) can produce out-of-order started -> start initiated signal sequence and cause unexpected node resubmission repeatedly.
Update the logic so that invalid state transition errors will only be warnings.
=> Fix unexpected worker resubmission from out of order start signals

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
* Currently the runtime task is executed in the IO executor service pool and mixed with other IO ops. Move runtime task execution to its own thread and not share it with the IO thread pool.
* Logging improvements on TE lifecycle.
=> RuntimeTask host thread + Logging improvements on TE

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
Disabled TEs are counted in cluster usages, which causes scaler not to respond properly when there are disabled TEs.
=> Exclude disabled TE in resource cluster usage

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorAllocationRequest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
Update the allocation logic in TE so that the scheduler will only put the requested node into a TE strictly using the smallest CPU cores to avoid having TEs spreading in different container sizes. Also, introduce an intermediate allocation request contract to help eventual decoupling/removal of Mesos classes.
=> Make TE allocation strictly following core number

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandler.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandlerAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/SetResourceClusterScalerStatusRequest.java
The goal of this PR is to introduce a new API to enable/disable scaler actor for a given SKU. This is useful when for example a new ASG is being provisioned to replace an existing one. During such operation we want to disable autoscaling for these ASGs until provisioning is done and the old ASG is marked as disabled. 
A timer is also added to re-enable the scaler in case something goes wrong and ASG provisioning couldn't complete successfully.  
This PR also aims to increase the cool down period for scaling down operations. The approach taken here is simplest possible which is hardcoding a factor of 5 over the configured cool down only for scale down operations.
=> Add API to enable/disable RC scaler

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
[Found from prod log scan]
In the control plane transition, in-error/crashed TE can have an initially empty state and gets an illegal state error if the control plane decides to unassign its current work. There is no action to take for the control plane at that point as it hasn't been able to re-establish a connection with TE. If the TE has a discrepancy on task assignment state if it should get handled when it gets back in the heartbeat message instead.
Reduced the catch scope and move the error log into a warning.
=> Handle TE invalid unAssigned state error

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActorTests.java
=> Fix ClusterAvailabilityRule

mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutorStarter.java
Adding rx.ring-buffer.size=1024 back seems to help in dealing with the expected backpressure consuming events from LWC source.
From https://www.uber.com/blog/rxjava-backpressure/
As demonstrated above, RxJava 1.x’s  rx.ring-buffer.size property stores the size of any in-memory ring buffers that RxJava uses when an Observable cannot keep up with rate of event emissions. The ring buffer size is explicitly set to a low number (8) because different platforms have different defaults for this value. While the Java Virtual Machine (JVM) default is 128 items per ring buffer, Android has a much lower limit of 16.
=> Add rx.ring-buffer.size to TE

mantis-common/build.gradle, mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageSchedulingInfo.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/IJobClustersManager.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobClusterRouteHandler.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobClusterRouteHandlerAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/HttpRequestMetrics.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/JobClustersRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/IJobClusterManager.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProtoTest.java
This diff supports updating a job cluster's scheduling info property.
=> Adding a new route to support updating scheduling info

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
=> Handle task executor gateway connection failures gracefully

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
Add CPU cores as an extra tag to help track the no resource available error. (Preferably I want the SKU id here but it's not directly available atm).
Remove "jobId" as it's redundant between "jobCluster" and "WorkerID".
=> Update NoResource error metric tags

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/CacheJobArtifactsRequest.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/worker/TaskExecutorGateway.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/JobArtifactsRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/ResourceClusterScaleRuleProto.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/IMantisPersistenceProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/ClassLoaderHandle.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/BlobStoreAwareClassLoaderHandle.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
The goal of this PR is to introduce a way to "pre"-cache job artifacts into Task Executors before jobs get scheduled in order to speed up job launch times (currently ~1 minute).
The idea is to inform TEs of which job artifacts to download from blobstore right after they registered themselves with the resource cluster. The detailed semantic follows these steps:
1. We tell the RC actor the set of artifacts to be cached on a given cluster (in the future we will add a new endpoint for this, but for now the information is stored in kvdal manually)
2. The TEs registers itself to the RC
3. The RC actor tells the TE which artifacts to cache (right now this process is best-effort, I think it's totally fine if some TEs fail to pre-cache and end-up with longer than expected job launch latencies).
=> Cache job artifacts on TE right after registration (to speed up job initialization time)

mantis-runtime/src/main/java/io/mantisrx/runtime/source/http/impl/HttpClientFactories.java
Add configurable options for the source client connection pool.
Move the default source client to disable the connection pool to avoid memory leak on pool cleanup.
=> Add source client connection pool options

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusterGatewayClient.java
Looks like the TE registers itself twice with the resource cluster actor in rapid succession which could lead to race conditions on caching artifacts.
* The first registration happens during [onStart](https://github.com/Netflix/mantis/blob/058657080e1341667b0fa38fb04b95d8160d560d/mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java#L188)
* The second one when ZK registers the new resource cluster (which in the case of first bootstrap of the TE is the same as the one registered during the first registration
In order to avoid double registration for the same RC the High avail service can simply verify whether the RC has actually changed before trying to reconnect to it.
Note: I'm not sure if there are edge cases I'm not considering. I can't think of …
=> Fix double TE registration against RC actor

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/UpgradeClusterContainersRequest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/NoopResourceClusterProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/ResourceClusterProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/ResourceClusterProviderAdapter.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/ResourceClusterProviderUpgradeRequest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterNonLeaderRedirectRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActorTests.java
Currently upgrade operation on RC is for the image version.
Support a new flag in upgrade RC to be able to upgrade Sku spec in upgrade operation.
=> Support SKU spec upgrade

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/FilterableMantisJobMetadataWritable.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/DataFormatAdapter.java
=> Make sure costs are emitted as part of the API Job metadata models

mantis-shaded/build.gradle
Adding zookeeper-jute since some of the classes required by curator-framework have been moved to this new module.
=> Adding zookeeper-jute as part of mantis-shaded

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/utils/StatusConstants.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Heartbeat.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RunningWorker.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
The purpose of this pull request (PR) is to ensure that a worker is promptly resubmitted in two specific situations: when a shutdown signal is detected by the Task Executor (TE) and when an exception occurs before the job enters the Launched state.
The TE can receive shutdown signals in various ways, with one well-known example being during Titus container migration. During container migration, Titus sends a sigkill signal to the running container, allowing it time to gracefully shut down. It is crucial for the TE to communicate with the master in a timely manner, informing it of the need to reschedule the worker due to the impending migration.
Similarly, if an exception is raised during task preparation, the TE must ask the master to reschedule the TE in another container. One such case …
=> Send heartbeat failure before shutting down TE

build.gradle, mantis-control-plane/mantis-control-plane-core/build.gradle, mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-server/mantis-server-worker/build.gradle
We found an issue with the curator recipes after the upgrade. As a result, we are rolling back to the older version of mantis-shaded.
=> Reverting mantis-shaded back to the old version

mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterNonLeaderRedirectRouteTest.java
ResourceClusterNonLeaderRedirectRouteTest -> testDisableTaskExecutorsRoute fails consistently in CI due to cache conflict.
=> Fix consistent test failure

mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/metrics/cgroups/CpuAcctsSubsystemProcess.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/metrics/cgroups/TestCpuAcctsSubsystemProcess.java
=> Perform conversions from microsecond to second correctly

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorNotFoundException.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/BaseRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java, mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
Calling GetTaskExecutorStatus gets 500 internal error + actor crash error.
Fix:
* Separate the calls and return the proper type for the actor ask.
* Add UTs.
=> Fix getTaskExecutorStatus failure on invalid TE ID

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobDiscoveryRouteHandlerAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/MantisStageMetadataImpl.java
Fix an old bug where job scheduleInfo discovery API with heartbeats will emit invalid info on running jobs.
E.g. `{"jobId":"HB_JobId","workerAssignments":null}` for `/assignmentresults/{JobId}?sendHB=true`
=> Fix job disoveryAPI with heartbeat parameter

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/JobMetadata.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorAllocationRequest.java, mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/domain/JobMetadataTest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/metrics/ResourceClusterActorMetrics.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
This PR is intended to improve the job artifact caching in these areas:
- Immediate downloads of newly registered job artifacts are ensured by _available_ Task Executors, eliminating the need for the first Task Executor restart. This approach is likely to speed up job initializations following the registration of a new job artifact.
- By attaching their clusters to a fast property (for now - we can have an API in the future), users have the option to adapt their job clusters for artifact caching. Master will ensure that the most recent artifact is always cached for the clusters configured in this way. This process occurs during each job launch. If any job's artifact has not been previously encountered, it will be included in the caching process after being added to the artifacts-to-cache …
=> Improving Job Artifact Caching: Immediate Downloads, Configurable Clusters, and Efficient Cleanup Mechanism

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java
Gateway registration runs as a detached future and the failure there is caused exception leak to the common thread pool and is not connected back to the state.
=> Handle TE gateway timeout

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterClientApi.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobDiscoveryRouteHandlerAkkaImpl.java
* Make the index total worker observable to cache the most recent result in case the subscription missed the very first scheduling info (and is stuck on the heartbeat message forever if no worker counts changes).
* Revert the control-plane side change so only the first SSE event contains the full info.
=> Fix runtime Index total worker observable + Revert control-plane change

mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationWritable.java, mantis-server/mantis-server-agent/build.gradle, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/ResourceManagerGatewayCxn.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/utils/ExponentialBackoffAbstractScheduledService.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/ResourceManagerGatewayCxnTest.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/RuntimeTaskImplExecutorTest.java
This PR adds the following things:
* Retry with random jittered exponential backoff - to prevent thundering herd of requests to master - to TE heartbeat. Retry configs can be changed
* Retry with random jittered exponential backoff - to prevent thundering herd of requests to master - to TE registration. Retry configs can be changed
* Counters: heartbeat timeouts, heartbeat failures, TE registration failures, TE disconnection failures 
Also ResourceManagerGatewayCxn has been moved to its own class since it's growing large.
Tests have been updated.
=> Implement a jittered exponential backoff retry policy for registration/heartbeat failures on the task executor

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-testcontainers/dependencies.lock
Add logs to validate dupe workers on the same worker index.
=> Add logs to check for dupe workers

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterGatewayAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
The guava rate limiter blocks during acquisition and causes degradation on API response for the akka routes.
=> Replace guava rate limiter

mantis-examples/mantis-examples-sine-function/src/main/java/io/mantisrx/mantis/examples/sinefunction/SineFunctionJob.java, mantis-runtime/src/main/java/io/mantisrx/runtime/source/Index.java
Observable received on index needs to be wrapped within cached behavior subject. The upstream observable received on index ctor is altered thus no longer a valid behaviorSubject and job sources use index's calls with blocking take(1) to get total worker number will cause the node to stuck.
=> Fix index obs

mantis-examples/mantis-examples-groupby-sample/build.gradle, mantis-examples/mantis-examples-jobconnector-sample/build.gradle, mantis-examples/mantis-examples-sine-function/build.gradle, mantis-examples/mantis-examples-synthetic-sourcejob/build.gradle, mantis-examples/mantis-examples-twitter-sample/build.gradle, mantis-examples/mantis-examples-wordcount/build.gradle
Since mantis-runtime now treats spectator API jars as compileOnly, the example jobs need to declare this directly.
=> Fix example job spectator

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
Fixing a few issues from prod.
* TE get info call exception escaped and caused actor failure. 
* TE RPC gateway connection saw a dead-letter error to the RPC worker. Such an error is not handled right now so the dead letter error will persist in the TE gateway. Added explicit reconnection call on failure to ensure the dead-letter worker gets refreshed.
=> Handle TE gateway connection error cases

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
Convert the get resourceGateway calls (which perform RPC connection inside) to return future and perform the actions on the future's completion instead of blocking and waiting.
=> Make calls on cacheArtifacts/reconnect non-blocking

mantis-common/src/main/java/io/mantisrx/common/metrics/MetricsServer.java
Revert to use id of the metricsGroupId in MetricsServer to fix the custom tagging.
(The original reason to switch to name to drop common tags is no longer required).
=> Revert metricsServer measurement group id

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
Add explicit error handling to the future of getting TE gateway in case the error happened before the compose logic.
=> Add error handling to gateway future

mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/SubscriptionStateHandlerImpl.java, mantis-runtime/src/main/java/io/mantisrx/runtime/executor/SinkPublisher.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutorStarter.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/RuntimeTaskImplExecutorTest.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java, mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
There is a race condition on the subscription handler where the current state can be empty if the subscription is established before the handler service is started, which causes non-perpetual jobs to silently fail at startup.
- Added handling + logs to this case.
- Added extra test in integration test.
- Removed sinkSubscriptionHandlerFactory on TaskExecutor level (not used anymore).
=> Fix unexpected sink side unsubscribe behavior 

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActorTests.java
Add disable TE requests during scale-down operation on RC.
=> Disable TEs on scaleDown

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
Problem:
TEs can get into connection problems where the TE gateway keeps failing causing frequent worker restarts and exhausting the idle pool.
* Refactor and clean up reconnection logic (handle the reconnection inside the TE gateway directly).
* Support scheduling rate limiter (this is supported via Fenzo on mesos but not supported on Titus).
=> TE connection improvement

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterClientApi.java, mantis-examples/mantis-examples-sine-function/src/main/java/io/mantisrx/mantis/examples/sinefunction/SineFunctionJob.java, mantis-runtime/src/main/java/io/mantisrx/runtime/source/Index.java, mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
Using behavior subject breaks the subscription propagation back to the connection (mantis API layer) and can cause a connection leak on the API layer.
Revert the behavior subject change and apply "replay" instead of "share" on the client side observable stream to ensure last valid data item is still available while having the source connection stream unsub properly.
=> Fix unsubsribe on mantisMasterClient schedulingChanges

mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-server/mantis-server-agent/build.gradle
Add support for calling java modules for java17. Tested via local mantis-helm chart deployment
=> add add-opens for java17

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterGatewayAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
=> Dynamic Rate Limiter

mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
=> Fix ratelimiter test failure

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationWritable.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/ResourceManagerGatewayCxn.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/RuntimeTaskImplExecutorTest.java
=> Use a separate directory to store registration information

mantis-client/src/main/java/io/mantisrx/client/MantisClient.java, mantis-client/src/main/java/io/mantisrx/client/SinkClientImpl.java, mantis-client/src/main/java/io/mantisrx/client/SinkConnectionsStatus.java, mantis-common/src/main/java/io/mantisrx/runtime/MantisJobState.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MasterClientWrapper.java
The current issues with unreliable periods identified on go/realtimesps largely arise from scale-up operations on the PlayAPI source job. Whenever a scale-up occurs, additional workers are introduced. However, the SPS tracker perceives this as a lack of connection with all up-stream workers and consequently flags the signal as unreliable. This is largely due to the current operational logic. Specifically, each SPS worker assesses the total number of workers in the source against the number it’s connected to. Since the SPS worker cannot connect to workers in the ‘launched’ state, this results in a discrepancy exceeding 5% (since the source is always scaled up by 40 units, surpassing 5% of the total). The discussion yesterday highlighted two potential solutions: 1) the total connections …
=> SinkConnectionsStatus to also provide running workers count

.github/CODEOWNERS
Got a lot of emails and push notifications about changes and comments on pull requests. As I do not actively work on Mantis right now, it's better to remove me from the default reviewers.
=> Remove liuml07 from default reviewers

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/MantisJobMetadataWritable.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/store/MantisStageMetadataWritable.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProviderTest.java
Currently, any failure during the loading job from the persistency layer step causes the job to be dropped without proper cleanup.
Here the logic is updated as follows:
* If two duplicate workers on the same stage index are found, load the one with the newer worker number to use as active.
* The dupe one with the older worker number then gets terminated in the job actor when it sends the heartbeat and doesn't match with the active worker number.
=> Fix losing job on control plane restart

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
After https://github.com/Netflix/mantis/pull/579 TEs won't send registration requests after restarting, so it's important to mark TEs as disabled on heartbeats. This check will only be performed the very first heartbeat TEs send after restart (when registration is null and fetched from the DB).
=> Fix disable path

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java
This PR addresses a problem encountered with TE allocation in scenarios where jobs have TEs with different resource specs that match the same SKU. For instance, if a job contains a TE with 1 core and another with 2 cores, and the smallest SKU available is a 2 core, both TEs will match the smallest SKU. This situation can lead to the same TE being incorrectly allocated to different workers, as currently the logic assumes that resource spec always matches the SKU size (which in a few cases it's not the case).
In order to address this issue, we now pass the list of already assigned TEs over to the matching logic, ensuring we aren't reusing them for other worker requests.
=> Fix duplicate TE allocation to multiple workers with different resource spec matching the same SKU 

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActorMetrics.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
Reduce the expiration time for disabled TE during scale-down.
Improve logging and metrics.
=> Reduce disable expiration on TE scale down

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/DataFormatAdapter.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobClusterDefinitionImpl.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/server/master/domain/DataFormatAdapterTest.java
Allow job cluster loading on disabled job cluster definitions if the cluster definition misses required parameters to maintain proper back compat.
=> Allow disabled job to load if it contains invalid state

build.gradle, mantis-client/dependencies.lock, mantis-connectors/mantis-connector-job/dependencies.lock, mantis-connectors/mantis-connector-publish/dependencies.lock, mantis-control-plane/mantis-control-plane-client/dependencies.lock, mantis-control-plane/mantis-control-plane-core/dependencies.lock, mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-server/dependencies.lock, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-store/mantis-control-plane-store-dynamodb/dependencies.lock, mantis-examples/mantis-examples-mantis-publish-sample/dependencies.lock, mantis-examples/mantis-examples-sine-function/dependencies.lock, mantis-publish/mantis-publish-core/dependencies.lock, mantis-publish/mantis-publish-netty-guice/dependencies.lock, mantis-publish/mantis-publish-netty/dependencies.lock, mantis-runtime-executor/dependencies.lock, mantis-runtime-loader/dependencies.lock, mantis-server/mantis-server-agent/dependencies.lock, mantis-server/mantis-server-worker-client/dependencies.lock, mantis-source-jobs/mantis-source-job-publish/dependencies.lock, mantis-testcontainers/dependencies.lock
=> Fix double comp

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/ExecuteStageRequest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v0/JobDiscoveryRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/JobsRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/resources/application.conf
Add client IP tracking to the log to get schedule Info to help detect unexpected callers.
Reduce some chatty logs.
=> Add clientIP to scheduleInfo API log + chatty log cleanup

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/MasterApiAkkaService.java
Added an https connection context that allows that caller of MasterAPIAkkaService to provide TLS settings, I've defined a new constructor that matches the old signature so this should be a no-op for existing usage.
=> Optional HTTPS connection context

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/JobIdNotFoundException.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterClientApi.java, mantis-control-plane/mantis-control-plane-client/src/test/java/io/mantisrx/server/master/client/MantisMasterClientApiTest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v0/JobDiscoveryRoute.java
We are seeing a high frequency of unexpected calls to the "assignmentResults" API to closed jobs in a prod instance, which turns out to be connections stuck in an infinite retry policy on the observable created by mantisClient.
The fix here added the error handling to both server API response (return 404 on closed jobs) and client-side (escape the infinite retry if getting 404 response).
=> Fix leaked schedulingChanges connections

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
TaskExecutor lifecycle is too early to set the MantisNettyEventsListenerFactory singleton. It has to be set up from the runtime. Since during the TaskExecutor lifecycle, the job is still not set up. So, tags like mantisJobId or mantisJobName are not available yet.
=> Moving where the MantisNettyEventsListenerFactory is being set

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/DisableTaskExecutorsRequest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManager.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorClusterUsageAkkaTest.java
Adding api to query disabled TEs.
[update]
Updating the logic for:
* Add condition for disabled TEs metrics to only include active (registered) TEs.
* Include disabled TEs in auto scaler usage so disabled TEs won't pollute the scale-up calculation.
=> Add GetDisabledTaskExecutors Api + scaler handling on disabled TEs

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/MasterApiAkkaService.java
Assigning `httpServerBuilder` with the result of `enableHttps()` - I'd forgotten to check how the builder was working, the scala implementation is returning a new copy on ever method call, not mutating itself. 
See code here: https://github.com/akka/akka-http/blob/0e2a451d93a2ed0b8c87ced245c21f563122e80d/akka-http-core/src/main/scala/akka/http/scaladsl/ServerBuilder.scala#L141
=> Reassigned httpServerBuilder after enableHttps

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java
The SSEWorkerConnection clients don't apply the client listener factory, thus missing certain metrics on the client side, e.g. tcpClient bytesRead.
The fix here is to re-apply the listener similar to how rxnetty clients got it.
=> Fix missing client metrics

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationUtils.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationWritable.java
Use metrics collector from configuration in `RuntimeTaskImpl`.
Currently `CgroupsMetricsCollector` is hard-coded in `RuntimeTaskImpl.java`, so if it is overridden using the ` mantis.taskexecutor.metrics.collector` field in the Mantis agent properties, that isn't respected. This change uses the dynamically loaded implementation of `MetricsCollector`.
This change is a continuation of https://github.com/Netflix/mantis/pull/648.
=> Use metrics collector from configuration in RuntimeTaskImpl.

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java, mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/JobAutoScaler.java, mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/JobAutoscalerManager.java, mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/JobMasterService.java, mantis-runtime-executor/src/test/java/io/mantisrx/server/worker/jobmaster/JobAutoScalerTest.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationUtils.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationWritable.java
This will allow runtime control over autoscaler, toggling on/off decisions to scale up and scale down a mantis job stage.
A use-case for this could be disabling autoscaler during a failover period to disable scale down.
=> Introduce job autoscaler manager

mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitor.java
It is possible that the DynamoDBMasterMonitor checks for the current leader more often than the underlying ByteBuffer is updated by the DynamoDB library.  In this case, we should rewind the buffer.
We can also optionally create a separate config for the lock client update and the monitor check leader interval to ensure check leader is called less frequently than the lock client updates.
=> Ensure Master Monitor Can Read Lock ByteBuffer More than Once

mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBLeaderElector.java, mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBStore.java
DynamoDB leadership election: return leadership success status in `tryToBecomeLeader`.
We would like to capture leadership metrics. This change allows users to extend the class and inject instrumentation of the `tryToBecomeLeader` loop.
Also, small bug fix for dynamoDB delete where we are using the incorrect tablename.
cc @kmg-stripe
=> DynamoDB leadership election: return leadership success status

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/JobAutoScaler.java
=> fix log message when scaleDownThreshold is met

mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitor.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBClientSingletonTest.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitorTest.java
This is an extension of @kmg-stripe 's fix in https://github.com/Netflix/mantis/pull/691 that is ready to merge.
The DynamoDBMasterMonitor had cases where it may propagate a `null` value when `getLatestMaster()` is called, despite having some protections against it. I've removed the `AtomicReference` to the latest and just rely on the `BehaviorSubject` to return the latest value.
=> DynamoDB Leader Monitor: On Next Should Always Provide MasterDescription

mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/ExecuteStageRequest.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/JobMetadata.java, mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/ExecuteStageRequestTest.java, mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/domain/JobMetadataTest.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/ExecuteStageRequestFactory.java, mantis-control-plane/mantis-control-plane-server/src/test/java/com/netflix/mantis/master/scheduler/TestHelpers.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestLifecycle.java, mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/RuntimeTask.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/RuntimeTaskImplExecutorTest.java
Expose `jobVersion`, `jobJarUrl` as part of RuntimeTask interface.
This allows us to add version and sha labels to our job metrics. We'd like these metric labels so we can monitor our automated job deploys.
=> expose jobVersion, jobJarUrl as part of RuntimeTask interface

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/LeadershipManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
LeadershipManagerZkImpl has no Zk dependencies. Therefore, we should rename it.
=> Rename LeadershipManagerZkImpl to LeadershipManagerImpl

.github/workflows/nebula-ci.yml, .github/workflows/nebula-publish.yml, .github/workflows/nebula-snapshot.yml, .github/workflows/push-docker-image.yml, baseline.gradle, build.gradle, gradle/wrapper/gradle-wrapper.properties, mantis-connectors/mantis-connector-job/build.gradle, mantis-connectors/mantis-connector-kafka/build.gradle, mantis-connectors/mantis-connector-publish/build.gradle, mantis-control-plane/mantis-control-plane-client/build.gradle, mantis-control-plane/mantis-control-plane-core/build.gradle, mantis-control-plane/mantis-control-plane-dynamodb/build.gradle, mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-store/mantis-control-plane-store-dynamodb/build.gradle, mantis-publish/mantis-publish-netty/build.gradle, mantis-server/mantis-server-agent/build.gradle, mantis-shaded/build.gradle
To fix the removed maven dependencies, the Nebula oss version + gradle version needs to be updated.
* New gradle (8.x) is also causing error on the extra copyLibs task in control-plane-core which now requires explicit declaration on downstream consumers.
* Baseline plugin new version requires jdk17. Disable for now.
=> Fix maven missing deps: upgrade nebula + gradle

gradle.properties, mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitor.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitorTest.java
We encountered an issue in which `DynamoDBMasterMonitor` would emit a `MASTER_NULL` value in the event of failing to read or decode the lock from DynamoDB. This caused some minor but unncessary churn as our agents believed the master had changed when it in fact had not. This can be further exacerbated by transient failures in Dynamo or throttling when querying Dynamo.
=> DynamoDBMasterMonitor: Don't publish MASTER_NULL on Dynamo failure

mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBStore.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBStoreTest.java
Also setting explicit pagination limit.
This should fix a pretty big problem:
We have hit a case where the master persistently thinks most jobs are inactive, so every time a new leader is elected most jobs are resubmitted.  Over time, new jobs have piled up (100s per cluster), which has made the problem worse, since Dynamo is only returning ~30 partition keys (jobIds from MantisWorkers).
=> Add Pagination to DynamoDB Query Calls

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
I forgot to update the previous PR with this fix.  We have enough cruft lying around from all of the churn, that we hit cases where we get a NPE when we cannot parse the worker payload in `getAllWorkersByJobId`.  This checks to ensure `workers` is not empty before referencing the first element of `workers`.
=> Fix WorkersByJobId: Filtered Workers Not Empty Check

mantis-client/src/main/java/io/mantisrx/client/MantisClient.java, mantis-client/src/main/java/io/mantisrx/client/MantisSSEJob.java, mantis-connectors/mantis-connector-job-source/build.gradle, mantis-connectors/mantis-connector-job-source/src/main/java/io/mantisrx/connector/job/core/MantisSourceJobConnector.java, mantis-connectors/mantis-connector-job-source/src/main/java/io/mantisrx/connector/job/core/MantisSourceJobConnectorFactory.java, mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/master/MasterDescription.java, mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitor.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBClientSingletonTest.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitorTest.java
1. All source job connectors have ZK config hard-coded due to parameter-less
`MantisSourceJobConnectorFactory`.  Configuring a `MantisClient` in this context
doesn't make sense, since we can reference the configured `HighAvailabilityServices`
2. `DynamoDBMasterMonitor` was erroneously logging parse errors when reading
leadership info from the DB.
3. `HighAvailabilityServicesImpl` was setting the leader state to NULL, which lead
to `ResourceClusterGatewayClient` constructing an invalid URI.  Updating to not
update the `ResourceClusterGatewayClient` when master is NULL.
=> Fixes to Source Job Connector and Master Monitor Logging

mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/BlobStore.java, mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/BlobStoreTest.java
Add support to a fallback blob store which will be used if the default storage cannot fetch the target file. This is used for blob store migration.
=> Support fallback blob store

mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/BlobStore.java
The underlying blob store use runtime exceptions for auth-related errors.
Switching catch to use base exception type.
=> Fix blobstore fallback error type

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterClientApi.java
In [some instances](https://github.com/Netflix/mantis/blob/1e29767d3517cd5763bf8c76cf707beb2e2c2760/mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java#L1916) the `GET assignmentresults` request can return a 400. Presently the `MantisMasterClientApi` will abandon the `GET assignmentresults` request on a 404 response signaling the job does not exist, but it treats all other status codes as retryable and enters a retry loop that tops out at `INT_MAX`. 
We're observing the agent getting into a state where a thread is effectively looping forever calling this endpoint despite the fact that the rest of the job has shut down.
=> MantisMasterClientApi: Handle HTTP 400 on GET assignmentresults

.github/workflows/nebula-ci.yml
[Previous builds](https://github.com/Netflix/mantis/actions/runs/10816646454/job/30008244181) are getting an error message due to the [deprecation](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) of some older github actions. This is an attempt to get our builds working again.
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```
=> Migrate CI upload-artifact action from v2 to v3

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/proto/JobClusterProtoAdapter.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobDefinitionResolver.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/MantisJobMetadataImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/DataFormatAdapter.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobClusterConfig.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobDefinition.java, mantis-control-plane/mantis-control-plane-server/src/test/java/com/netflix/mantis/master/scheduler/TestHelpers.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterAkkaTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobDefinitionResolverTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/LabelManagerTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerAkkaTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestHelper.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestLifecycle.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/server/master/domain/DataFormatAdapterTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/server/master/domain/JobClusterConfigTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/server/master/persistence/FileBasedStoreTest.java
This is a fork of @sarahwada-stripe's PR (#706).  I'll take this over, since she is OOO.
@Andyz26 - I addressed the few comments in the original PR.  I'll get back to this next week and will add the requested backwards compatible tests.
I wanted to open a PR to kick off a discussion about the jobJarURL format that the mantis-master expects. It looks like the mantis-master expects the jobJarURL in the JobConfig to have a single path component, e.g. `https://my-job-jar.zip`, and drops path information when there are multiple path elements, e.g. `https://git-sha-prefix/my-job-jar.zip`.
A reproduction of the behavior that I've observed is:
1. Write a jobConfig with `jobJarFileLocation` like `https://git-sha-prefix/my-job-jar.zip`
2. Master submits a job to agent with the jobJarUrl …
=>  use jobJarUrl instead of artifactName to avoid stripping path prefixes

mantis-control-plane/mantis-control-plane-dynamodb/build.gradle, mantis-control-plane/mantis-control-plane-server/build.gradle, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/SLAEnforcer.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobClusterRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobDiscoveryRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobStatusRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobClustersRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobDiscoveryStreamRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobsRouteTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterAkkaTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/SLAEnforcerTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerAkkaTest.java, mantis-control-plane/mantis-control-plane-store/mantis-control-plane-store-dynamodb/build.gradle, settings.gradle
Stripe has a very autodeploy focused approach to code. As a result our Mantis jobs are forcibly submitted each time their code is updated. This becomes very painful for us when users are developing new jobs, as they may merge code that will never transition from `Accepted` to `Launched` dozens of times. They effectively denial of service the platform eventually by consuming all resources available. Nothing can start, on-call gets activated, and manual cleanup is necessary.
Our users have generally wondered why the SLA max isn't stopping this from happening. They expect that if they set a max of 1 that the platform will not allow an infinite number of jobs to pile up in accepted. It is a reasonable assumption but not how things work today.
A solution to this is that the SLA is enforced on …
=> SLA Max: Config to apply to Accepted + Launched jobs.

mantis-runtime/src/main/java/io/mantisrx/runtime/parameter/ParameterUtils.java
We're experimenting with increasing the throughput of our "Ingest" (source) jobs. Typical rules of thumb on thread pool sizes for IO bound task are generally larger than the number of CPUs available as IO threads spend a lot of time waiting (not CPU bound). We're also using 8 vCPU boxes but I figured there was little harm in adding a lot of headroom.
=> Increase mantis.sse.numConsumerThreads maximum from 8 to 64.

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerAkkaTest.java, mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
I would like to revive this [PR](https://github.com/Netflix/mantis/pull/549) from @hmitnflx to use the last launched job state instead of the last submitted to avoid downstream consumer jobs being stuck with a new submission at an error state or too long time to allocate resources.
* Replace discovery subject source from last submitted to last launched.
* Fixed and added UT.
=> Change Job discovery to use most recent launched job

.github/workflows/nebula-ci.yml, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterAkkaTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerAkkaTest.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/MantisHttpClientImpl.java
Currently, when a new job gets submitted, all the workers get scheduled in batch to have an all-or-nothing manner. However, the job actor heartbeat check will also try to re-schedule a worker if it's "stuck" in the allocation phase for too long (based on the worker-heartbeat-timeout config). Thus the batch scheduling gets invalidated after some timeout (which could be problematic for larger jobs when we need more time to get the requested resource allocated from the cluster auto scaler).
Behavior changes here:
* Batch scheduling failure will retry without attempt limit. (We will rely on the cancel request message from its job actor to interrupt).
* JobActor heartbeat routine will not act on unscheduled workers.
* fixed the akka-tests and added these back to the CI build.
=> Prevent per-node scheduling fallback during batch scheduling retry 

mantis-runtime/src/main/java/io/mantisrx/runtime/GroupToScalar.java, mantis-runtime/src/main/java/io/mantisrx/runtime/KeyValueStageConfig.java, mantis-runtime/src/main/java/io/mantisrx/runtime/ScalarToGroup.java
The default concurrency for `ScalarToGroup` and `GroupToScalar` stages is `-1` and thus relies on the number of inner observables when executing the stage. There may be cases such as CPU bound stages where the user wants fine grained control over how many threads are executing the stage logic.
Some discussion in #681 indicates a desire for this, but I agree with @calvin681 that changing defaults shouldn't be done lightly as users have come to expect certain threading behavior with the stages. I think this represents a compromise where unaware users can continue with the default and power users can begin to control threading.
=> Allow user specified concurrency for Scalar to Group and Group to Scalar

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
Increasing the default schedule retries config (since the initial scheduling on batch is consolidated to honor the backoff it should be safe now to use a larger retry max to reduce jobs stuck on no resource not retrying anymore).
The follow-up work here could be to extend this to retry forever (e.g. if no resource is available for this scheduling request, keep retrying with proper backoff delay), but given the risk, I will defer this change till we gather more confidence with the new behavior.
=> Increase schedule retries

mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/client/SseWorkerConnectionTest.java
The `SseWorkerConnection` uses a `DropOperator` with a metric named suffixed with `withBuffer` set in the [SseWorkerConnectionFunction](https://github.com/Netflix/mantis/blob/master/mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnectionFunction.java#L61) class. The class takes a `bufferSize` parameter but does nothing with it! I've had the illusion that we've been buffering here for darn near a decade!
This change is pretty straightforward implementation. `rebatchRequests` simply sends `n` requests into the `DropOperator` and continues to stay ahead of the requests made by the downstream by up to n. There is a batching implementation inside of the operator that RxJava uses to implement this.
Users could then set the buffer with the: …
=> Add a buffering functionality to the SseWorkerConnection

mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusterGatewayClient.java, mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/CoreConfiguration.java, mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java
We found a case where agents with shutdown workers got leaked:
* A job with multiple workers is being shut down.
* Some workers receive the shutdown signals and terminate the running workers. However, some workers fail to receive the signals (timeout, etc.) and continue to be alive. Now, all upstream traffic is re-distributed to these workers, and they become very busy (peaked CPU/network usage).
* Retried kill signals cannot reach these workers while the worker's host agent's heartbeat message to the control plane timed out, causing them to be leaked.
Improvements:
* increase heartbeat connection client's thread priority
* increase heartbeat connection timeout settings.
=> Handle overloaded agent's heartbeat timeout

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisScheduler.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactoryImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareScheduler.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestMigrationTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/scheduler/FakeMantisScheduler.java
A recent change removed worker resubmits when workers are stuck in accepted: https://github.com/Netflix/mantis/pull/719
Our underlying scheduler will not retry the allocations, so we need a way to conditionally enable the ability to resubmit.
I did not see unit tests for the functionality that was removed.  I'd be happy to add them, but would like to get this merged first, since we had to pin master to a different version than the agents to avoid stuck workers.
=> Resubmit Worker Allocations

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
In some edge cases, where the node fails after accepting worker submission, the submitted request's handling failure is currently ignored, thus leaving the failed worker in a stuck state if the job is not fully launched yet (still in the initial batch scheduling state).
fix:
trigger scheduling failure to retry.
=> Handle submitted worker failure

mantis-rxcontrol/src/main/java/io/mantisrx/control/clutch/ExperimentalClutchConfigurator.java
`stat.getPercentile(0)` would cause this exception 
```
2024-12-02 21:05:45.787 ERROR 1171 --- [tionScheduler-1] i.m.s.w.j.JobAutoScaler                  : got onError in JobAutoScaler
org.apache.commons.math3.exception.OutOfRangeException: out of bounds quantile value: 0, must be in (0, 100]
at org.apache.commons.math3.stat.descriptive.rank.Percentile.setQuantile(Percentile.java:398)
at org.apache.commons.math3.stat.descriptive.DescriptiveStatistics.getPercentile(DescriptiveStatistics.java:442)
at io.mantisrx.control.clutch.ExperimentalClutchConfigurator.logStatsSummary(ExperimentalClutchConfigurator.java:137)
at io.mantisrx.control.clutch.ExperimentalClutchConfigurator.lambda$call$9(ExperimentalClutchConfigurator.java:114)
at rx.internal.util.ActionObserver.onNext(ActionObserver.java:39) …
```
=> Fix clutch rps

mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/MantisHttpClientImpl.java, mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java, mantis-server/mantis-server-worker-client/src/test/java/io/mantisrx/server/worker/client/SseWorkerConnectionTest.java
We noticed that when the SSE connection triggered "doOnError", the SSE HTTP client was closed internally (via resetConn) but the following "retryWhen" operation started an infinite retry action on the closed HTTP Client (and every retry failed right away since the client is not going to start the actual connection).
Solution:
Refactor to split reset and close operations on the SSE client so that the "doOnErro" within the retry loop will only reset instead of closing the client. Added an outer "doOnError" to make sure the client gets closed once the retry loop is broken.
=> Fix sse connection infinite retry failure

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/JobAutoScaler.java, mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/control/actuators/ClutchMantisStageActuator.java, mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/control/actuators/MantisStageActuator.java, mantis-runtime-executor/src/test/java/io/mantisrx/server/worker/jobmaster/control/actuators/MantisStageActuatorTest.java, mantis-rxcontrol/src/test/java/io/mantisrx/control/clutch/ExperimentalControlLoopTest.java
While monitoring the autoscaling behavior of our clusters, I observed an unexpected scale-down event in the shared MRE source ~3 AM PST, despite having scaling down disabled (new feature introduced for the next live event). This anomaly was not present in the PlayAPI source, which behaved correctly under the same conditions.
Upon investigation, I discovered that the `ExperimentalControlLoop` class, used by the Clutch RPS scaling policy, was incorrectly updating the `currentSize` to the `desiredSize` even when the actuator did not perform a scale-down due to scaling being disabled. This led to a discrepancy between the `currentSize` and the actual cluster size, causing future scaling decisions to be based on incorrect data.
This behavior resulted in a critical issue where, upon scaling up, …
=> Fix Incorrect Cluster Size Update in ExperimentalControlLoop When Scaling Down is Disabled

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
If a node marked as disabled was never destroyed by the host cluster and maintained heartbeats (thus, its executor state remained valid in memory), it would remain disabled until the next leader's re-election.
Fix:
On disable node expiration, ensure the internal state (if still valid) is reset to be not disabled.
=> re-enable disabled node on expiry

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/worker/IMantisWorkerMetadata.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/worker/MantisWorkerMetadataImpl.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestLifecycle.java
Problem:
The missing heartbeat logic relies on the last HB timestamp to determine whether it should be re-submitted by the job actor or the scheduler. This creates a problem for workers failed right after getting scheduled but before it's able to emit the first heartbeat message. This problem gets amplified when we have higher transient worker startup failures due to other issues.
Solution:
Instead of last heartbeat, use the launched event status to decide whether the job actor should start taking over the job resubmission from the scheduler.
=> Ensure worker failed before first heartbeat gets resubmission

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorClusterUsageAkkaTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
Problem:
When a TE is returned from here to be used for scheduling, its state remain active until the scheduler trigger another message to update (lock) the state. However when large number of the requests are active at the same time on same sku, the gap between here and the message to lock the state can be large so another schedule request message can be in between and got the same set of TEs. 
Solution:
To avoid this, a lease is added to each TE state (based on last scheduled usage timestamp) to temporarily lock the TE to be used again. Since this is only lock between actor messages and lease duration can be short.
* Also fixed a NPE from the node state update call.
=> Fix scheduler double booking task executors

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestLifecycle.java
A race condition was introduced from #731 when a heartbeat check happened between launch event and first heartbeat and can trigger NPE on the actor. 
Refactored the condition check on the case above + improve UTs to cover the related states.
=> Fix worker no heartbeat race condition

mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitor.java, mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitorSingleton.java, mantis-control-plane/mantis-control-plane-dynamodb/src/test/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitorSingletonTest.java
We encountered an issue where the MasterMonitor's `shutdown` method was called somewhere.  This led to clients relying on updates to the MasterMonitor stopping receiving updates but they had no mechanism of knowing that the monitor they were subscribed to was no longer updating because the observable was not completed and getting the latest version would continue to return the last known value (even though that value was not updated).
We were deciding between either using a Singleton or tracking down `shutdown` calls to `MasterMonitor` and ensuring that usages could resubscribe if necessary.  The latter seemed like it would be prone to breakage in the future (e.g. particularly with the master observable). Additionally, a Singleton pattern seemed fitting given that almost every reasonable …
=> Use a singleton for DynamoDbMasterMonitor

.github/CODEOWNERS
=> Removing Sundaram from the list of codeowners

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterAkkaTest.java
The update artifact request's artifact field is mapped to the "url" request field. In #708 the extra "http://" prefix is added to the job jar url causing double prefix in the existing job config.
=> Fix cluster artifact update back compatibility

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterAkkaTest.java
Needs to handle both https and http url in the back compatibility change for legacy jar artifact url.
=> Fix https jar url in update artifact request

mantis-remote-observable/src/main/java/io/reactivex/mantis/remote/observable/RemoteObservable.java
Adds a similar change to [721](https://github.com/Netflix/mantis/pull/721) to the connections in RemoteObservable. We're experiencing a lot more stage to stage dropping on the ARM machines with 15Gbit we're using at Stripe. The user needs to set `workerClient.buffer.size` to take advantage of this.
=> Add a rebatch call to RemoteObservable connections between stages.

.github/workflows/nebula-ci.yml, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestLifecycle.java
It seems like there is a race condition where a recently launched worker has not sent a heartbeat, the duration is still within the missed heartbeat threshold and the JobActor treats the lack of heartbeat with a resubmit.
=> Handle Case Where Recently Launched Worker Does Not Immediately Heartbeat

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/domain/JobClusterDefinitionImpl.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterAkkaTest.java, mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
Currently, initializing a job cluster with an incorrect cron schedule that cannot be parsed by Quartz silently errors with a warning log. We should return a response instead
=> report error creating cron

mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBConfig.java, mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBMasterMonitorSingleton.java
The `DynamoDBMasterMonitor` presently ensures a clean shutdown when the JVM shutdown hook is called. This works well for Master instances as it will release the lock on the leader election. However in when running on the agent this has the downside of sometimes shutting down before other threads that require master communication. The result is workers that stay stuck until a `180s` heartbeat timeout. Furthermore closing the lock client has no benefit for the agents -- they don't lock it.
This would enable us to configure agents to let this thread keep running. It is configured as a daemon thread so it will not prevent the JVM from shutting down.
=> DynamoDBMasterMonitor: Add option to disable shutdown hook.

mantis-connectors/mantis-connector-job-source/src/main/java/io/mantisrx/connector/job/core/AbstractJobSource.java, mantis-connectors/mantis-connector-job-source/src/main/java/io/mantisrx/connector/job/core/AbstractSourceJobSource.java, mantis-connectors/mantis-connector-job-source/src/main/java/io/mantisrx/connector/job/source/JobSource.java, mantis-runtime/src/main/java/io/mantisrx/runtime/parameter/SourceJobParameters.java
a followup on https://github.com/Netflix/mantis/pull/747
allow users to pass in additional query params like availabilityZone={availabilityZone} to JobSource
=> Update JobSource to take in additional query params

mantis-connectors/mantis-connector-job-source/src/main/java/io/mantisrx/connector/job/core/AbstractJobSource.java
Fix the bug introduced in https://github.com/Netflix/mantis/pull/748 where getDefaultSinkParams didn't update with additional params
=> Fix getDefaultSinkParams not returning additionalParams

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
When implementing the scheduling hook I made some inner classes public but not the encapsulating class so I cannot access it https://github.com/Netflix/mantis/pull/753
=> Fixing class visibility

.github/workflows/nebula-ci.yml, .github/workflows/push-docker-image.yml, mantis-control-plane/mantis-control-plane-server/build.gradle
Actions Cache v1 and v2 are being [deprecated](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down) March 01, 2025.
=> Upgrade to actions-cache v4

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobHeartbeatTimeoutTest.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestLifecycle.java, mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
This PR fixes a critical bug in the worker heartbeat timeout detection logic that was causing workers stuck in the `Launched` state to not be properly resubmitted. The issue was due to a time unit mismatch in the `JobActor` class where `Instant.ofEpochSecond()` was incorrectly used instead of `Instant.ofEpochMilli()` when calculating the time since a worker was launched.
The core issue was in `JobActor.java` where the system was incorrectly converting the worker's launch timestamp:
```java
// Before:
boolean noTimelyHeartbeatSinceLaunched = !workerMeta.getLastHeartbeatAt().isPresent()
&& Duration.between(Instant.ofEpochSecond(workerMeta.getLaunchedAt()), currentTime).getSeconds() > missedHeartBeatToleranceSecs;
// After:
boolean noTimelyHeartbeatSinceLaunched = …
```
=> Fix Worker Heartbeat Timeout Logic for Launched Workers

mantis-network/src/main/java/io/reactivex/mantis/network/push/PushServer.java
In pushServer the slotId tag's cardinality is too big and costly and we can achieve similar granularity using a combination of clientId + infra tags.
=> Replace slotId tag with clientId in PushServer

mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java, mantis-runtime/src/main/java/io/mantisrx/runtime/parameter/ParameterUtils.java
Note: V2 scaler for dynamic scaler rule support is fully back-compatible with v1 scaler so no change is expected on existing jobs.
=> Enable v2 scaler by default

mantis-network/src/main/java/io/reactivex/mantis/network/push/ConnectionManager.java
As title, changing two very long log lines' level from `info` to `debug`
=> update log level from into to debug for two big log lines

mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/EventDrainer.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/EventProcessor.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/StreamManager.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/api/Event.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/internal/discovery/mantisapi/DefaultMantisApiClient.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/internal/mql/MQL.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/internal/mql/MQLSubscription.java, mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/proto/MantisServerSubscriptionEnvelope.java
Found a number of opportunities in code to fix warnings, simplify code. Changed code to apply these fixes
=> Add variety of cleanups, fix warnings, improve code/performance

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
Support default tag config as fallback on artifact loading failure.
=> Support default tag config as fallback on artifact loading failure

mantis-common/src/main/java/io/mantisrx/runtime/MantisJobDefinition.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/utils/JobRouteUtils.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v0/JobClusterRoute.java, mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/JobsRoute.java, mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
1. add validation for numOfPorts, as it's not supported right now 
2. move shared job request validation logic to utils 
3. remove wrapped request in taskexecutor, as there's no subscriber registered on this wrapped object in the current code base
@Andyz26
=> Move common code to utils and cleanup

mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
- TE will be set to disabled state when scale down, add logs to check how many TE stayed in the archived state are not in disabled state.
- the archived state contains all the ghost TEs and other explicitly removed TE, adding this log to check if we could filter the ghost ones from this archived state
=> Add log to check #TE archived was not in disabled state
