Netflix/mantis

- mantis-network/build.gradle
Pin MQL to v3.1.x
- [X ] `./gradlew build` compiles code correctly
- [X ] Added new tests where applicable
- [ X] `./gradlew test` passes all tests
- [X ] Extended README or added javadocs where applicable
- [ X] Added copyright headers for new files from `CONTRIBUTING.md`
> pin mql to 3.1.x

- mantis-server/mantis-server-worker/build.gradle
> Bump Mesos version.

- docs/docs/index.md
- docs/mkdocs.yml
> Add components to docs site.

- docs/README.md
Add readme instructions for building and releasing the public docs site.
> Docs readme

- docker-compose.yml
- mantis-server/mantis-server-worker/Dockerfile
- mantis-server/mantis-server-worker/build.gradle
> Upgrade Mesos to 1.3.2.

- mantis-common/src/main/java/io/mantisrx/common/WorkerPorts.java
I'd like to use this from the caller to print a more detailed message on exceptions.
> Minor: Add `sinkPort` to `WorkerPorts#toString`.

- mantis-common/src/main/java/io/reactivx/mantis/operators/DropOperator.java
- mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java
- remove requested and subscribe gauges from DropOperator
- remove host and port tags due to high cardinality issue
To reduce metrics cost removing 
> Remove unused gauges from DropOperator

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/clutch/ClutchAutoScaler.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/clutch/experimental/MantisClutchConfigurationSelector.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/control/controllers/PIDController.java
- mantis-shaded/build.gradle
> Add Guava 18 to shaded libs

- docs/docs/developing/mre.md
> Add mantis publish properties to docs

- docs/docs/reference/mql.md
Add example and text for filter event with specific attribute.
> Add description for msql to filter event with specific attribute

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/DataDroppedPayloadSetter.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ReportStatusServiceHttpImpl.java
lower log level for benign errors
> adjust log levels

- README.md
Update README with context for 2.x branch
> 2.x branch

- mantis-client/build.gradle
- mantis-common/src/main/java/io/mantisrx/common/metrics/Metrics.java
- mantis-common/src/main/java/io/mantisrx/common/metrics/Timer.java
- mantis-common/src/main/java/io/mantisrx/common/metrics/spectator/TimerImpl.java
We have support for counters and gauges. Timers would be nice.
> Add support for specator timers.

- mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/committer/IcebergCommitterStage.java
- mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/committer/metrics/CommitterMetrics.java
Replace latency metric with gauge for timer.
> Use timer for commit latency.

- gradle/check.gradle
Getting build failures from PMD. Opening this PR to see if bumping the version fixes the issue.
> Update pmd version.

- mantis-common/src/test/java/io/mantisrx/common/compression/CompressionUtilsTest.java
> Close buffered readers in tests.

- docs/docs/develop/connectors/iceberg.md
- mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/config/WriterConfig.java
> Update Iceberg sink docs.

- docs/docs/develop/connectors/iceberg.md
This is no longer true since workers can have multiple writers.
> Update docs: remove old section.

- mantis-examples/mantis-examples-groupby-sample/src/main/java/com/netflix/mantis/samples/stage/AggregationStage.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/StageExecutors.java
- Allow concurrency to be configured for group to scalar stages by setting the job parameter mantis.stageConcurrency
- add log statements in groupBy sample
- [x ] `./gradlew test` passes all tests
> Configurable concurrency in Group-Scalar stage

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Auto-generate release notes from commits.
> Add release drafter github action.

- build.gradle
> Update netflixoss to 9.4.1

- docs/mkdocs.yml
- mantis-network/src/main/java/io/reactivex/mantis/network/push/Chunker.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/TimedChunker.java
Add metrics to TimedChunker to track potential dropped events
> Add metrics to TimedChunker to track potential dropped events

- docs/docs/develop/connectors/iceberg.md
> Trival fix code snippet highlight in iceberg.md

- mantis-client/src/main/java/io/mantisrx/client/SinkClientImpl.java
- mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/SseWorkerConnection.java
Add logging to SinkClient to track uncleaned connections
> Add logging to SinkClient to track uncleaned connections

- mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/AbstractSubscriptionTracker.java
> Fix spotless checks in AbstractSubscriptionTracker

- mantis-client/src/main/java/io/mantisrx/client/JobSinkLocator.java
- mantis-client/src/main/java/io/mantisrx/client/MantisClient.java
- mantis-client/src/main/java/io/mantisrx/client/MantisSSEJob.java
- mantis-client/src/main/java/io/mantisrx/client/SinkConnection.java
Do some code cleanup during my code walk. Goal is not to change any functional logic but refine it in a clearer/cleaner way.
- ~[ ] Added new tests where applicable~
- ~[ ] Extended README or added javadocs where applicable~
- ~[ ] Added copyright headers for new files from `CONTRIBUTING.md`~
> Code minor cleanup in mantis-client module

- mantis-common/src/test/java/io/mantisrx/common/compression/CompressionUtilsTest.java
- mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterEndToEndTest.java
- mantis-network/src/test/java/io/reactivex/mantis/network/push/TimedChunkerTest.java
- mantis-publish/mantis-publish-core/src/test/java/io/mantisrx/publish/DefaultSubscriptionTrackerTest.java
- spotless changes only
- ignore flaky and failing tests
> Ignore failing and flaky tests for now

- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestHelper.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Task.java
Just a simple refactor of Task by indenting the file using 4 spaces instead of 2.
> Indent task using 4 spaces

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MachineDefinitionUtils.java
- mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/Point.java
> Refactoring a few classes

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/WorkerId.java
- mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/domain/WorkerIdTest.java
> Making WorkerId serializable by both jackson and Java

- .github/workflows/nebula-ci.yml
> Upload test results from the ci workflow

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
> Fixing trace log

- build.gradle
- mantis-examples/mantis-examples-groupby-sample/build.gradle
- mantis-examples/mantis-examples-mantis-publish-web-sample/build.gradle
> adding jcenter

- build.gradle
- mantis-examples/mantis-examples-groupby-sample/build.gradle
> Let's see if this works

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorID.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/SchedulingService.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisScheduler.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareScheduler.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestMigrationTests.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/scheduler/FakeMantisScheduler.java
> Making the initialization of tasks based on task executor IDs

- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/control/plane/resource/cluster/ResourceClustersHostManagerActorTests.java
Fix flaky test case in ResourceClustersHostManagerActorTests.
> Fix flaky test case in ResourceClustersHostManagerActorTests

- .github/workflows/nebula-publish.yml
- .github/workflows/nebula-snapshot.yml
> Updating publish and snapshot workflows

- mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/ExecuteStageRequestTest.java
> Adding a test to verify if execute stage request is serializable

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/MesosSchedulerCallbackHandler.java
> Disabling reconciliation temporarily

- build.gradle
- mantis-common/src/main/java/io/mantisrx/common/JsonSerializer.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/MantisJobMetadataImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterReadRouteTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterTest.java
- mantis-shaded/build.gradle
> Upgrading mantis-shaded dependency

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ClassLoaderHandle.java
> Making ClassLoaderHandle public

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/master/ZookeeperMasterMonitor.java
> Fixing master description bug

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
> Making worker backwards compatible'

- mantis-common/src/main/java/io/mantisrx/common/JsonSerializer.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/ExecuteStageRequest.java
- mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/ExecuteStageRequestTest.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/VirtualMachineMasterServiceMesosImpl.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/mesos/MesosExecutorCallbackHandler.java
Related to https://github.com/Netflix/mantis/issues/194
> Using the same serializer during serialization of TaskInfo

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/master/ZookeeperMasterMonitor.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/zookeeper/CuratorService.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
> Start zookeeper service eagerly for all mantis workers

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ExecuteStageRequestService.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Task.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/TaskExecutor.java
This is needed to support Mantis Jobs written using springboot.
> Support passing MantisJob to Mantis Worker's Mesos Main as well as to other Task abstractions

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
We need MantisWorker::start to be blocking as the mesos implementation at Netflix makes certain assumptions about it. This diff gets it back to the old behavior.
> Refactoring MantisWorker so that the start behavior is consistent with v1.x version

- .github/workflows/nebula-snapshot.yml
> Publish snapshot from every branch

- .github/workflows/nebula-snapshot.yml
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ExecuteStageRequestService.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/Task.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/mesos/VirualMachineWorkerServiceMesosImpl.java
> Add extra logs

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/InMemoryOnlyResourceClusterStorageProvider.java
Update test resource storage provider to use concurrent map.
> Fix flaky route test

- mantis-network/src/main/java/io/reactivex/mantis/network/push/ObservableTrigger.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/PushServers.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/GroupToGroup.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/GroupToScalar.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/KeyToKey.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/KeyToScalar.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/KeyValueStageConfig.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/KeyedStages.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/NettyCodec.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/ScalarStages.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/ScalarToGroup.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/ScalarToKey.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/ScalarToScalar.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/SourceHolder.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/StageConfig.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/Stages.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/StageExecutors.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/WorkerConsumerRemoteObservable.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
- Preview for follow-up to supporting custom key encoders
- Code refactor to remove redundant generic datatype specification
- Refactor netty to mantis-common Codec in a separate location that can be code shared
> Code refactor

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareSchedulerActor.java
We can ignore the TaskNotFoundException error coming from TaskExecutorGateway as this means the cancellation request need not be retried.
> During task cancellation using TaskExecutor's gateway, ignore certain types of errors

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/MantisStageMetadataImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/worker/JobWorker.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
During oncall, I noticed that some requests were returning incorrectly formatted messages.
I took this opportunity to fix formatter errors.
> fix string formatting arg specifiers

- mantis-common/src/main/java/io/mantisrx/runtime/MachineDefinition.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MachineDefinitionUtils.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/TaskExecutor.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/config/WorkerConfiguration.java
- mantis-server/mantis-server-worker/src/test/java/io/mantisrx/server/worker/ResourceManagerGatewayCxnTest.java
> Ensuring the right network bandwidth is set during registration

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandler.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandlerAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/GetClusterIdleInstancesRequest.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/GetClusterIdleInstancesResponse.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/GetClusterUsageResponse.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/ProvisionResourceClusterRequest.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/ResourceClusterScaleRuleProto.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/ResourceClusterScaleSpec.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/InMemoryOnlyResourceClusterStorageProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/ResourceClusterStorageProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/ResourceClusterStorageProviderAdapter.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/resourceprovider/SimpleFileResourceClusterStorageProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/writable/ResourceClusterScaleRulesWritable.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/payloads/ResourceClustersPayloads.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterNonLeaderRedirectRouteTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActorTests.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/SimpleFileResourceStorageProviderTests.java
- mantis-control-plane/mantis-control-plane-server/src/test/resources/testpayloads/ResourceClusterScaleRuleCreate.json
- mantis-control-plane/mantis-control-plane-server/src/test/resources/testpayloads/ResourceClusterScaleRulesCreate.json
- mantis-control-plane/mantis-control-plane-server/src/test/resources/testpayloads/ResourceClusterScaleRulesResult.json
Add resource scaler actor to support resource cluster level scaling up/down using scale rules per cluster + sku.
> Add resource cluster scaler actor 

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersLeaderExclusiveRoute.java
> Reduce heartbeat log level

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/akka/MantisActorSupervisorStrategy.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
Cleaning up logs at a few places.
> Adding more logging in the supervisor strategy

- .github/PULL_REQUEST_TEMPLATE.md
> Changing pull request template to not include copyright headers

- mantis-common/src/main/java/io/mantisrx/runtime/descriptor/StageScalingPolicy.java
- mantis-common/src/test/java/io/mantisrx/runtime/descriptor/StageScalingPolicyTest.java
> Cleaning more objectmapper usages

- build.gradle
Pulling in the latest mantis shaded.
> Upgrading mantis shaded

- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
Fix UT `ResourceClusterActorTest.testInitializationAfterRestar`
> Fix UT ResourceClusterActorTest.testInitializationAfterRestar

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/ObservableTrigger.java
> Log exception on job kill

- mantis-network/src/main/java/io/reactivex/mantis/network/push/ObservableTrigger.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/clutch/rps/RpsClutchConfigurationSelector.java
> Prevent divide by 0 error

- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MantisMasterClientApi.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/ObservableTrigger.java
Return observable error so the retry logic can kick in
> Return observable error so the retry logic can kick in

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/metrics/MetricsFactory.java
> Make MetricsFactory::getCommonTags public

- build.gradle
- mantis-control-plane/mantis-control-plane-client/build.gradle
- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/TaskStatusUpdateHandlerImpl.java
- mantis-control-plane/mantis-control-plane-core/build.gradle
- mantis-control-plane/mantis-control-plane-server/build.gradle
> Getting rid of unnecessary deps

- .github/workflows/nebula-snapshot.yml
- build.gradle
> Getting rid of pull_request_target

- .github/workflows/nebula-snapshot.yml
> Add env protection rule

- .github/workflows/nebula-snapshot.yml
> Fix indentation

- .github/workflows/nebula-snapshot.yml
> Make pr comments sticky

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
> Handle null taskExecutor state

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/proto/JobClusterProtoAdapter.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/payloads/JobClusterPayloads.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobClusterRouteTest.java
Fix translation from MantisJobDefinition to job cluster creation request contracts to include the proper resource cluster tag.
> Fix RC jobcluster creation

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/ResourceClusterAwareScheduler.java
> Getting rid of an unnecessary log error

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactoryImpl.java
Multiple Akka dispatcher threads can enter the scheduler actor creation together and cause conflicts in actor creation.
Switched the map holding these actors to the concurrent map.
> Fix race condition during SchedulerActor creation

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobArtifactRouteHandlerImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/JobArtifactsRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobArtifactProto.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/IMantisPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
> Support contains in job artifact search

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v0/JobClusterRouteTest.java
> Fix typo thats preventing deleting failed workers from table

- mantis-connectors/mantis-connector-iceberg/build.gradle
- mantis-connectors/mantis-connector-iceberg/dependencies.lock
- mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStageTest.java
> Upgrade Iceberg to 0.14.x

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/DeadLetterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
Cleaning up how dead letters are handled.
> Cleaning up DeadLetterMessages

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerMetricsCollector.java
> Log the exception

- mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/DefaultIcebergWriter.java
> Iceberg sink uses ZSTD compression codec if not configured per table

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorRegistration.java
- mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/master/resourcecluster/TaskExecutorRegistrationTest.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
> Fix case sensitive TE attributes

- build.gradle
Update mantis-shaded version to v2.0.0
> Update mantis-shaded version to v2.0

- docs/docs/updates/gsoc2023-ideas.md
> feat: add ui asks for gsoc 2023

- docs/mkdocs.yml
This looks cleaner compared to listing all the headings in a document.
> Decreasing the toc_depth

- mantis-common/src/main/java/io/mantisrx/server/core/ServiceRegistry.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/WorkerPublisherRemoteObservable.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/sink/ServerSentEventsSink.java
> Making sure MantisPropertiesLoader can be set

- docs/docs/updates/gsoc2023-ideas.md
> Add project and fixup mentors for other projects

- docs/docs/updates/gsoc2023-ideas.md
> Adding proposal for replacing the metrics implementation in Mantis

- build.gradle
This should fix the build issue as seen by others.
> Updating the gradle plugin to 7.0.0

- build.gradle
- mantis-client/dependencies.lock
- mantis-connectors/mantis-connector-job/dependencies.lock
- mantis-connectors/mantis-connector-publish/dependencies.lock
- mantis-control-plane/mantis-control-plane-client/dependencies.lock
- mantis-control-plane/mantis-control-plane-core/dependencies.lock
- mantis-control-plane/mantis-control-plane-server/dependencies.lock
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManager.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/metrics/ResourceClusterActorMetrics.java
- mantis-runtime-loader/dependencies.lock
- mantis-server/mantis-server-agent/dependencies.lock
- mantis-server/mantis-server-worker-client/dependencies.lock
- mantis-server/mantis-server-worker/dependencies.lock
- mantis-source-jobs/mantis-source-job-publish/dependencies.lock
As title suggests. Tested in-house and metrics make it to Atlas with the expected name `ResourceClusterActor_<name>` and tag `resourceCluster`.
> Monitor Resource Overview

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/metrics/cgroups/CpuAcctsSubsystemProcess.java
- mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/metrics/cgroups/TestCpuAcctsSubsystemProcess.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/ResourceUsagePayloadSetter.java
> Additional logging to figure out why peak cpu stats is not correct

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerMetricsCollector.java
> Group worker lifecycle metrics by resource cluster

- mantis-common/src/main/java/com/mantisrx/common/utils/NettyUtils.java
- mantis-common/src/main/java/io/mantisrx/common/MantisProperties.java
- mantis-common/src/main/java/io/mantisrx/common/properties/DefaultMantisPropertiesLoader.java
- mantis-connectors/mantis-connector-kafka/src/main/java/io/mantisrx/connector/kafka/source/MantisKafkaConsumerConfig.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/metrics/MetricsFactory.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/stats/MetricStringConstants.java
- mantis-examples/mantis-examples-synthetic-sourcejob/src/main/java/io/mantisrx/sourcejob/synthetic/sink/TaggedEventFilter.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/LocalJobExecutorNetworked.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/StageExecutors.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/jobmaster/JobAutoScaler.java
- mantis-source-jobs/mantis-source-job-kafka/src/main/java/io/mantisrx/sourcejob/kafka/sink/TaggedEventFilter.java
- mantis-source-jobs/mantis-source-job-publish/src/main/java/io/mantisrx/sourcejobs/publish/core/Utils.java
* Make props read from system env wrapped with system properties read since these props are now in system props in TE.
* Add worker number + stage number tag names to support existing metrics dashboard/alerts.
> [Back Compat] Wrap env parameter read + metrics tags

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerMetricsCollector.java
> To be consistent with other metrics

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/DisableTaskExecutorsRequest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/payloads/ResourceClustersPayloads.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterNonLeaderRedirectRouteTest.java
Make disable TE request expiration configurable from request.
> Configurable Disable TE expiry

- mantis-common/src/main/java/io/mantisrx/server/core/ServiceRegistry.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/MantisWorker.java
> Finding who is setting mantis fast properties

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
> Fix NPE publishResourceClusterMetricBySKU

- build.gradle
- mantis-client/dependencies.lock
- mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterStage.java
- mantis-connectors/mantis-connector-iceberg/src/test/java/io/mantisrx/connector/iceberg/sink/writer/IcebergWriterEndToEndTest.java
- mantis-connectors/mantis-connector-job/dependencies.lock
- mantis-connectors/mantis-connector-publish/dependencies.lock
- mantis-control-plane/mantis-control-plane-client/dependencies.lock
- mantis-control-plane/mantis-control-plane-core/build.gradle
- mantis-control-plane/mantis-control-plane-core/dependencies.lock
- mantis-control-plane/mantis-control-plane-server/dependencies.lock
- mantis-examples/mantis-examples-mantis-publish-sample/dependencies.lock
- mantis-publish/mantis-publish-netty-guice/dependencies.lock
- mantis-publish/mantis-publish-netty/dependencies.lock
- mantis-runtime-loader/dependencies.lock
- mantis-runtime/build.gradle
- mantis-runtime/dependencies.lock
- mantis-runtime/src/main/java/io/mantisrx/runtime/Context.java
- mantis-runtime/src/main/java/io/mantisrx/runtime/executor/LocalJobExecutorNetworked.java
- mantis-server/mantis-server-agent/dependencies.lock
- mantis-server/mantis-server-worker-client/dependencies.lock
- mantis-server/mantis-server-worker/dependencies.lock
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/WorkerExecutionOperationsNetworkStage.java
- mantis-source-jobs/mantis-source-job-publish/dependencies.lock
> Pass classloader to ThreadFactoryBuilder

- mantis-control-plane/mantis-control-plane-server/build.gradle
> deal with flaky tests by retrying

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
> Try except publishResourceClusterMetricBySKU

- mantis-client/dependencies.lock
- mantis-common/src/main/java/io/mantisrx/common/WorkerConstants.java
- mantis-connectors/mantis-connector-job/dependencies.lock
- mantis-connectors/mantis-connector-publish/dependencies.lock
- mantis-control-plane/mantis-control-plane-client/dependencies.lock
- mantis-control-plane/mantis-control-plane-core/dependencies.lock
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/TaskExecutorRegistration.java
- mantis-control-plane/mantis-control-plane-server/build.gradle
- mantis-control-plane/mantis-control-plane-server/dependencies.lock
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-examples/mantis-examples-mantis-publish-sample/dependencies.lock
- mantis-publish/mantis-publish-netty-guice/dependencies.lock
- mantis-publish/mantis-publish-netty/dependencies.lock
- mantis-runtime-loader/dependencies.lock
- mantis-server/mantis-server-agent/dependencies.lock
- mantis-server/mantis-server-worker-client/dependencies.lock
- mantis-server/mantis-server-worker/dependencies.lock
- mantis-source-jobs/mantis-source-job-publish/dependencies.lock
> Add asg tag

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/metrics/ResourceClusterActorMetrics.java
> Add TE heartbeat timeout metric

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
> Making sure the job is loaded even if there are no workers

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
> Emit a metric in case we are not able to load workers

- mantis-client/src/main/java/io/mantisrx/client/MantisClient.java
- mantis-client/src/main/java/io/mantisrx/client/examples/ConnectToNamedJob.java
- mantis-common/src/main/java/com/mantisrx/common/utils/Services.java
- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/MasterClientWrapper.java
- mantis-server/mantis-server-worker-client/src/main/java/io/mantisrx/server/worker/client/WorkerMetricsClient.java
> Starting the HighAvailabilityServices

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandler.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/ResourceClusterRouteHandlerAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
> Fix setScalerStatus endpoint

- .github/workflows/push-docker-image.yml
- mantis-control-plane/Dockerfile
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/MasterApiAkkaService.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v0/AgentClusterRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
- mantis-control-plane/mantis-control-plane-server/src/main/resources/master-docker.properties
- mantis-control-plane/mantis-control-plane-server/src/main/resources/master-local.properties
- mantis-server/mantis-server-agent/Dockerfile
- mantis-server/mantis-server-agent/build.gradle
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/AgentV2Main.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/LocalFileSystemFactory.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/config/ConfigurationFactory.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/config/StaticPropertiesConfigurationFactory.java
- mantis-server/mantis-server-agent/src/main/resources/META-INF/services/io.mantisrx.server.agent.FileSystemFactory
- mantis-server/mantis-server-agent/src/main/resources/agent-docker.properties
- mantis-server/mantis-server-agent/src/main/resources/agent.properties
- mantis-server/mantis-server-worker/Dockerfile
> github action to build and publish Docker images on release/RC builds

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
> Setting heartbeats to debug level

- mantis-common/src/main/java/io/mantisrx/common/metrics/Metrics.java
- mantis-common/src/main/java/io/mantisrx/common/metrics/MetricsRegistry.java
> Fixing identification issue in Metrics::Builder

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/proto/JobClusterProtoAdapter.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/JobClusterTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobClusterManagerTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestHelper.java
> Adding the capability to submit the latest job cluster configuration as a job

- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobTestHelper.java
> Fixing tests

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/AgentV2Main.java
> Also include system properties as well for WorkerConfiguration

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/LeadershipManagerZkImpl.java
> Adding a gauge to track time since the master node became leader

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/worker/TaskExecutorGateway.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/ResourceClusterScaleRuleProto.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/IMantisPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
> Add remove/get job artifacts to cache endpoints.

- mantis-connectors/mantis-connector-iceberg/src/main/java/io/mantisrx/connector/iceberg/sink/committer/IcebergCommitterStage.java
> [Connectors] Add table information to IcebergCommitter

- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java
- mantis-server/mantis-server-agent/src/main/resources/agent.properties
> Making sure the client is talking to the right port when connecting locally

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/FilterableMantisJobMetadataWritable.java
- mantis-control-plane/mantis-control-plane-server/src/test/resources/persistence/job_metadata_view.json
> Making sure costs was being emitted

- mantis-runtime/src/main/java/io/mantisrx/runtime/source/http/impl/HttpSourceImpl.java
> Making sure connection errors don't create a new message signature every single time

- build.gradle
> Updating mantis-shaded

- build.gradle
- mantis-shaded/build.gradle
- mantis-shaded/dependencies.lock
> Updating curator version

- build.gradle
- mantis-shaded/dependencies.lock
> Updating version of mantis shaded

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/ExecuteStageRequest.java
- mantis-control-plane/mantis-control-plane-core/src/test/java/io/mantisrx/server/core/ExecuteStageRequestTest.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/ExecuteStageRequestFactory.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/mesos/VirtualMachineMasterServiceMesosImpl.java
- mantis-server/mantis-server-agent/src/test/java/io/mantisrx/server/agent/RuntimeTaskImplExecutorTest.java
- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/VirtualMachineWorkerServiceLocalImpl.java
> Pass “mantisUser” to the task executor during task submission

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/Jackson.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/TaskExecutorState.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/GetTaskExecutorsRequest.java
> Adding support for querying registered/available/busy task executors by SKU ID or any other attribute

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/worker/TaskExecutorGateway.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutor.java
> Adding a new RPC to find out if the task executor is registered or not.

- mantis-common/src/main/java/io/mantisrx/server/core/ServiceRegistry.java
> Making sure ServiceRegistry does not spit out an exception unless needed

- mantis-server/mantis-server-agent/buildDockerImage.sh
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/TaskExecutorStarter.java
> Create script to build mantisagent docker image locally

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceCluster.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/ResourceClustersNonLeaderRedirectRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/DisableTaskExecutorsRequest.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/proto/DisableTaskExecutorsRequest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/ResourceClusterNonLeaderRedirectRouteTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/DisableTaskExecutorsRequestTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
> Disable task executors by ID

- docs/docs/develop/querying/sampling.md
- docs/docs/operate/heartbeat.md
- docs/mkdocs.yml
1. Add docs for customizing worker heartbeats and timeout.
2. Explain in detail how sticky sampling works. Also, provide an example!
> update docs to add worker heartbeat; also detail sticky sampling

- settings.gradle
> Ignoring mantis test containers

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
- mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfiguration.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/AgentV2Main.java
- mantis-server/mantis-server-agent/src/main/resources/agent-docker.properties
- mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
- settings.gradle
* Fix agent property overrides: move env var based config value to part of worker config directly. Remove agent entry overrides.
* Re-enable test container test.
> fix agent overrides

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
Ensure the cron state gets cleanup during any init error.
> Handle cron init error

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
Upon master restart, the resource cluster actor is repeatedly crashing due to NPE thrown during caching job artifact routine. Although it's currently unknown why that's the case (we should spend a bit of time in the future to figure that out), for the time being it's important we never crash the actor in this non-critical function.
> Avoid throwing npe when either TE gateway can't be reached or if caching job artifacts fails 

- mantis-server/mantis-server-worker/src/main/java/io/mantisrx/server/worker/RuntimeTaskImpl.java
> Emitting log.error without string formatting

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
It may be that the timer is set to trigger too early before the expiration time. In these instances, we should set up another timer for a later moment.
> Make sure to expire set scaler request

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/handlers/JobDiscoveryRouteHandlerAkkaImpl.java
For API "/assignmentresults/{JOB_ID}?sendHB=true" the returned heartbeat info doesn't update to the actual info observable thus the heartbeat events are always empty after the initial response (which is from the actual observable).
Validated locally.
> Fix job discovery AssignmentResult

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/DeadLetterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
Add message type for non-json message letters.
> Improve dead letter log

- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusterGatewayClient.java
> Increase RC gateway timeouts

- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/client/HighAvailabilityServicesUtil.java
- mantis-control-plane/mantis-control-plane-client/src/main/java/io/mantisrx/server/master/resourcecluster/ResourceClusterGatewayClient.java
- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/CoreConfiguration.java
- mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/config/WorkerConfigurationWritable.java
> Adding a way to configure the resource cluster http client

- mantis-common/src/main/java/io/mantisrx/common/metrics/LoggingMetricsPublisher.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/MasterApiAkkaService.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/MasterApiMetrics.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/BaseRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
- mantis-control-plane/mantis-control-plane-server/src/main/resources/master-docker.properties
- mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
* New metrics in http server/routes.
* Attach metered mailbox to resource cluster actor.
> Improve actor and http api server metrics

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/MasterApiMetrics.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/v1/BaseRoute.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterGatewayAkkaImpl.java
> Add throttle request metrics

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterGatewayAkkaImpl.java
Add resourceGatewayAkkaImpl level metrics.
> Add ResourceGatewayAkkaImpl metrics

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/HadoopFileSystemBlobStore.java
> Fix race condition when fetching the same artifact

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
> Make isJobArtifactCachingEnabled onfigurable

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/BlobStore.java
- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/HadoopFileSystemBlobStore.java
> Make blob store thread safe

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/scheduler/MantisSchedulerFactoryImpl.java
> Cleaning up log line 

- mantis-shaded/build.gradle
- mantis-shaded/dependencies.lock
> [JDK17] Updating the zookeeper version and dependency locks for mantis-shaded

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
> Adding a metric to count the number of jobs stuck in accepted state

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActor.java
Add validation to ensure the Sku id in the resource cluster spec is rejected if it contains any trailing number.
> Validate sku id

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
> Changing the log level to debug

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/ResourceManagerGatewayCxn.java
> ResourceGatewayConnection debug log cleanup

- mantis-publish/mantis-publish-core/src/main/java/io/mantisrx/publish/StreamManager.java
> Only synchronize key code blocks in stream manager

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterGatewayAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/MasterMain.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
Refactor the config hack to use the dynamic property.
Update default value.
> Refactor rate limiter config to dynamic property

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
> Feature flagging batch scheduling

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/com/netflix/mantis/master/scheduler/TestHelpers.java
> Fix feature flag condition

- .github/workflows/nebula-ci.yml
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/CompletedJobStore.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterProto.java
- mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
> Handling failure to initialize job clusters better

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
> Convert num jobs stuck in accepted state into a gauge from a counter

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/IMantisPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActorTests.java
> Order completed jobs returned by IMantisPersistenceProvider

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/JobClustersManagerService.java
> Tracking leader initialization latency as a metric

- mantis-server/mantis-server-agent/src/main/java/io/mantisrx/server/agent/MachineDefinitionUtils.java
> Ensuring memory read from the machine is converted into MBs

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/api/akka/route/utils/JobRouteUtils.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/CompletedJobStore.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/proto/JobClusterManagerProto.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/IMantisPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/KeyValueBasedPersistenceProvider.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
This change is a pure refactor
> Renaming endExclusive to startExclusive

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
> Add log on core map addition

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/JobClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/persistence/MantisJobStore.java
Reduce non-actionable chatty logs' level.
> Cleanup chatty logs

- mantis-control-plane/mantis-control-plane-core/src/main/java/io/mantisrx/server/core/domain/JobArtifact.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/api/akka/route/v1/JobArtifactSerdeTest.java
Add tags field to JobArtifact class to support artifact tagging.
> Add tags field to JobArtifact

- mantis-runtime-loader/src/main/java/io/mantisrx/runtime/loader/SubscriptionStateHandlerImpl.java
> Adding more logs to SubscriptionStateHandler

- mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/clutch/ClutchAutoScaler.java
This change aims to ensure that the clutch autoscaling policies are consistent for all jobs. Specifically, the JVM memory will now be used as the value to determine if a job should be autoscaled based on memory, as opposed to the container memory. This is important because scaling based on container memory may not be a good metric due to how the JVM allocates memory. For more information, please refer to https://stackoverflow.com/questions/30458195/does-gc-release-back-memory-to-os.
Initially, I considered converting `io.mantisrx.server.worker.jobmaster.JobAutoScaler.Event` to `com.netflix.control.clutch.Event` and feeding it into the `io.mantisrx.server.worker.jobmaster.clutch.ClutchAutoScaler` to standardize the input for all autoscalers. However, this would require a major refactor, …
> Use JVM Memory instead of Memory in the ClutchAutoScaler

- .github/workflows/push-docker-image.yml
> Build both amd64 & arm64 images

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerTests.java
During the process of adding size metadata to an existing SKU and initiating corresponding ASG updates, TEs from both new and existing ASGs are now grouped separately in the resource cluster actor, i.e., one with size and one without. Due to this, issues may arise during task migrations as it's not predictable which TEs will be chosen by the scheduler. While, instead, we want to always use TEs from the latest ASGs.
This PR enhances our scheduling logic to solve this problem. Specifically, the `findBestGroupBySizeNameMatch` and `findBestGroupByFitnessCalculator` functions will now prefer TE groups with "younger" generation (aka higher ASG name). This effectively ensures that the newer ASG (with a higher generation value), resulting from a SKU upgrade, will be preferably used over the older …
> Prioritize latest generation TEs in scheduling during SKU upgrades

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/server/master/config/MasterConfiguration.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorClusterUsageAkkaTest.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/resourcecluster/ResourceClusterActorTest.java
This PR makes the fitness calculator configurable.
> Making the fitness calculator configurable

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterActor.java
The default actor supervisor strategy {MantisActorSupervisorStrategy} for all actors is using resume/stop but for resource cluster actors they need to be restarted from error so we don't have a leader running without needed RC actors.
Patch the RC actor to use a local strategy to restart all the time.
> fix rcActor supervisor

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
Issue:
Sometimes, the underlying store isn't available for the extensive writes made to update nextWorkerNumberToUse. An exception is thrown cascaded upstream preventing further writes and updates to worker from JobActor. To handle it, we tolerate some (consecutive) write failures for this call before propagating the exception upstream.
Invariant:
This is fine from a constraints perspective. Here's why: On new mantis master leader election, job and worker state is read from the DB. If the worker count was synced correctly no issue. If not and there were extra workers than workerMax stored in DB, those extra workers will be killed when TEs send heartbeat. If not and workerMax in DB is higher than actual workers, we'll schedule those workers on leader election.
Explain context and other …
> Allow failures setting nextWorkerNumberToUse

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterAkkaImpl.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClusterScalerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersHostManagerActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ResourceClustersManagerActor.java
Fix slow APIs (update/upgrade) gateway timeout.
> Fix Resource cluster API timeout

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerRegistryV2.java
Adding a metric to track the number of status events (before turning on status event logging).
> Track statusEvent count

- mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/ResourceUsagePayloadSetter.java
- mantis-server/mantis-server-agent/src/main/resources/agent-docker.properties
- mantis-server/mantis-server-agent/src/main/resources/agent.properties
- mantis-testcontainers/src/test/java/TestContainerHelloWorld.java
> Fixing cpu limit

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/events/WorkerMetricsCollector.java
> Adding some debug log to mantis scheduling to understand what is slow

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
> Add debug logs on scheduling logic

- mantis-common/src/main/java/com/mantisrx/common/utils/MantisSSEConstants.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/AsyncConnection.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/PushServer.java
- mantis-network/src/main/java/io/reactivex/mantis/network/push/PushServerSse.java
- mantis-network/src/test/java/io/reactivex/mantis/network/push/ConsistentHashingRouterTest.java
Add an `availabilityZone` field to `AsyncConnection` which can then later be accessed in the routers for in-az request routing
> Add availabilityZone to AsyncConnection

- mantis-runtime/src/main/java/io/mantisrx/runtime/sink/ServerSentEventsSink.java
Add a `withRouter` to `ServerSentEventsSink` builder to allow users to plug in a customized router instead of using the default round robin one
example use case: route requests to the same availability zone
cc @crioux-stripe
> Add withRouter to SSESink

- mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/JobAutoScaler.java
- mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/jobmaster/rules/ScalerControllerActor.java
Add a few metrics at job auto scaler level.
* Track auto scaler version using scaler id (job id + rule id)
* Metrics in scaler and metrics' request.
> Add jobAutoScaler level metrics

- mantis-control-plane/mantis-control-plane-dynamodb/src/main/java/io/mantisrx/extensions/dynamodb/DynamoDBLeaderElector.java
> Added log to indicate when we became leader

- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/jobcluster/job/JobActor.java
- mantis-control-plane/mantis-control-plane-server/src/main/java/io/mantisrx/master/resourcecluster/ExecutorStateManagerImpl.java
- mantis-control-plane/mantis-control-plane-server/src/test/java/io/mantisrx/master/jobcluster/job/JobScaleUpDownTests.java
This reverts commit 3b0c92f1b6efaa61664c943f1b490e18272dc395.
Temp revert batch scale up to mitigate scaler behavior issues.
> Revert "Fix Worker Request flow to properly use batching (#775)"

- mantis-runtime-executor/src/main/java/io/mantisrx/server/worker/RunningWorker.java
1. we don't need metric group since only one metric is logged, updated to use the registry directly
> Update worker failure metric
